/**
 * @file host.response
 * @description defines response for host entity
 * @created 2019-08-29 00:39:36
 * @author Desk Now Dev Team
 * @meta Response Code: 50XX, 51XX
*/

import HTTP from "./code.response";

export const MSG: any = {
    en: {
        NOT_FOUND: "Host not found",
        NO_STATE_DATA: 'Aceess Denied.',
        COMPANY_NOT_FOUND: "Company not found",
        LOGIN_SUCCESSFULL: "Login successfully",
        Email_NOT_VERIFIED: "Host email is not verified",
        EMAIL_ALREADY_EXISTS: "This email already exist",
        PHONE_ALREADY_EXISTS: "This phone number already exists",
        SIGNUP_SUCCESSFULLY: "Signup successfully, one time passcode sent to your mobile number",
        OTP_SENT_SUCCESSFULLY: "OTP sent successfully",
        OTP_INVALID: "Invalid OTP",
        URL_INVALID: "Invalid URL",
        OTP_VERIFIED: "OTP verified successfully",
        OTP_EXPIRED: "OTP expired",
        INCORRECT_PASSWORD: "Password is incorrect",
        LOGIN_SUCCESSFULLY: "User login successfully",
        ALREADY_BLOCKED: "Host is already blocked",
        USER_BLOCKED_SUCCESSFULLY: "Host  blocked successfully",
        USER_ALREADY_ACTIVE: "Host is already active",
        USER_UNBLOCKED_SUCCESSFULLY: "Host unblocked successfully",
        USER_ALREADY_DELETED: "Host already deleted",
        USER_DELETED_SUCCESSFULLY: "Host deleted successfully",
        USER_VERIFIED_SUCCESSFULLY: "Host verified successfully",
        USER_ALREADY_VERIFIED: "Host already verified",
        USER_IS_BLOCKED: "Your account is blocked from admin",
        PROFILE_UPDATED: "Profile has been updated successfully",
        COMPANY_DETAILS_SAVED: "Your company details has been saved successfully",
        COMPANY_DETAILS: "Successful",
        COMPANY_DETAILS_UPDATED: "Your company details has been updated successfully.",
        PROPERTY_SPACE_ADDED: "Property space added successfully",
        DUPLICATE_SPACE_ID: "Duplicate space id found",
        DUPLICATE_PRICING: "Duplicate pricing found",
        ACCOUNT_BLOCKED: "Your account has been temporarily blocked",
        PHONE_NOT_MATCHED: "Phone number not matched",
        PHONE_UPDATED: "Phone number updated successfully",
        COMPANY_ALREADY_EXISTS: "Company already exists",
        STRIPE_NOT_SETUP: 'Stripe account not setup',
        DUPLICATE_PARTNER: 'Partner already associated with another property', //new 
        DUPLICATE_EMPLOYEE: 'Duplicate employee selected',
        UNITS_NOT_AVAILABLE: 'Units Not Available',
        NOT_ALLOWED: 'Partner not allowed',
        NO_PAYOUT_AMOUNT : 'Amount is too small'
    },
    cs: {
        DUPLICATE_PARTNER: 'Partner already associated with another property', //new 
        DUPLICATE_EMPLOYEE: 'Duplicate employee selected',
        UNITS_NOT_AVAILABLE: 'Units Not Available',
        NOT_ALLOWED: 'Partner not allowed',
        NOT_FOUND: "Hostitel nebyl nalezen",
        NO_STATE_DATA: "Přístup odepřen.",
        COMPANY_NOT_FOUND: "Společnost nebyla nalezena",
        LOGIN_SUCCESSFULL: "Přihlášení bylo úspěšné",
        Email_NOT_VERIFIED: "E-mail hostitele není ověřen",
        EMAIL_ALREADY_EXISTS: "Tento e-mail již existuje",
        PHONE_ALREADY_EXISTS: "Toto telefonní číslo již existuje",
        SIGNUP_SUCCESSFULLY: "Registrace proběhla úspěšně, jednorázový přístupový kód byl odeslán na vaše telefonní číslo",
        OTP_SENT_SUCCESSFULLY: "OTP kód byl úspěšně odeslán",
        OTP_INVALID: "Neplatný OTP kód",
        URL_INVALID: "Neplatná URL adresa",
        OTP_VERIFIED: "OTP kód byl úspěšně ověřen",
        OTP_EXPIRED: "Platnost OTP kódu vypršela",
        INCORRECT_PASSWORD: "Nesprávné heslo",
        LOGIN_SUCCESSFULLY: "Přihlášení uživatele bylo úspěšné",
        ALREADY_BLOCKED: "Hostitel je již zablokován",
        USER_BLOCKED_SUCCESSFULLY: "Hostitel byl úspěšně zablokován",
        USER_ALREADY_ACTIVE: "Hostitel je již aktivní",
        USER_UNBLOCKED_SUCCESSFULLY: "Hostitel byl úspěšně odblokován",
        USER_ALREADY_DELETED: "Hostitel byl již smazán",
        USER_DELETED_SUCCESSFULLY: "Hostitel byl úspěšně smazán",
        USER_VERIFIED_SUCCESSFULLY: "Hostitel byl úspěšně ověřen",
        USER_ALREADY_VERIFIED: "Hostitel byl již ověřen",
        USER_IS_BLOCKED: "Váš účet je zablokován správcem",
        PROFILE_UPDATED: "Profil byl úspěšně aktualizován",
        COMPANY_DETAILS_SAVED: "Detail společnosti byl úspěšně uložen",
        COMPANY_DETAILS: "Úspěšné",
        COMPANY_DETAILS_UPDATED: "Detail společnosti byl úspěšně aktualizován.",
        PROPERTY_SPACE_ADDED: "Prostor v nemovitosti byl úspěšně přidán",
        DUPLICATE_SPACE_ID: "Bylo nalezeno duplicitní ID prostoru",
        ACCOUNT_BLOCKED: "Váš účet byl dočasně zablokován",
        PHONE_NOT_MATCHED: "Telefonní číslo se neshoduje",
        PHONE_UPDATED: "Telefonní číslo bylo úspěšně aktualizováno",
        COMPANY_ALREADY_EXISTS: "Společnost již existuje",
        STRIPE_NOT_SETUP: "Stripe účet není nastaven",
        NO_PAYOUT_AMOUNT : 'Amount is too small'
    },
    nl: {
        DUPLICATE_PARTNER: 'Partner already associated with another property', //new 
        DUPLICATE_EMPLOYEE: 'Duplicate employee selected',
        UNITS_NOT_AVAILABLE: 'Units Not Available',
        NOT_ALLOWED: 'Partner not allowed',
        NOT_FOUND: "Host niet gevonden",
        NO_STATE_DATA: "Toegang geweigerd.",
        COMPANY_NOT_FOUND: "Bedrijf niet gevonden",
        LOGIN_SUCCESSFULL: "Succesvolle aanmelding",
        Email_NOT_VERIFIED: "E-mailadres van host is niet geverifieerd",
        EMAIL_ALREADY_EXISTS: "Het opgegeven e-mailadres bestaat al",
        PHONE_ALREADY_EXISTS: "Dit telefoonnummer bestaat al",
        SIGNUP_SUCCESSFULLY: "Succesvol aangemeld, er is een eenmalig wachtwoord verzonden naar uw mobiele nummer",
        OTP_SENT_SUCCESSFULLY: "OTP is succesvol verzonden",
        OTP_INVALID: "Ongeldige OTP",
        URL_INVALID: "Ongeldige URL",
        OTP_VERIFIED: "OTP succesvol bevestigd.",
        OTP_EXPIRED: "OTP is verlopen",
        INCORRECT_PASSWORD: "Wachtwoord is onjuist",
        LOGIN_SUCCESSFULLY: "Succesvolle aanmelding door gebruiker",
        ALREADY_BLOCKED: "Host is al geblokkeerd",
        USER_BLOCKED_SUCCESSFULLY: "Host succesvol geblokkeerd",
        USER_ALREADY_ACTIVE: "Host is al actief",
        USER_UNBLOCKED_SUCCESSFULLY: "Host succesvol gedeblokkeerd",
        USER_ALREADY_DELETED: "Host is al verwijderd",
        USER_DELETED_SUCCESSFULLY: "Host succesvol verwijderd",
        USER_VERIFIED_SUCCESSFULLY: "Host succesvol geverifieerd.",
        USER_ALREADY_VERIFIED: "Host al geverifieerd",
        USER_IS_BLOCKED: "Uw account is geblokkeerd voor beheerder",
        PROFILE_UPDATED: "Uw profiel is succesvol bijgewerkt",
        COMPANY_DETAILS_SAVED: "Uw bedrijfsgegevens zijn succesvol opgeslagen",
        COMPANY_DETAILS: "Gelukt",
        COMPANY_DETAILS_UPDATED: "Uw bedrijfsgegevens zijn succesvol bijgewerkt.",
        PROPERTY_SPACE_ADDED: "Accommodatie-space succesvol toegevoegd",
        DUPLICATE_SPACE_ID: "Dubbele space-ID gevonden",
        ACCOUNT_BLOCKED: "Uw account is tijdelijk geblokkeerd",
        PHONE_NOT_MATCHED: "Telefoonnummer komt niet overeen",
        PHONE_UPDATED: "Telefoonnummer succesvol bijgewerkt",
        COMPANY_ALREADY_EXISTS: "Bedrijf bestaat al",
        STRIPE_NOT_SETUP: "Stripe-account niet ingesteld",
        NO_PAYOUT_AMOUNT : 'Amount is too small'
    },
    fr: {
        DUPLICATE_PARTNER: 'Partner already associated with another property', //new 
        DUPLICATE_EMPLOYEE: 'Duplicate employee selected',
        UNITS_NOT_AVAILABLE: 'Units Not Available',
        NOT_ALLOWED: 'Partner not allowed',
        NOT_FOUND: "Hôte introuvable",
        NO_STATE_DATA: "Accès refusé.",
        COMPANY_NOT_FOUND: "Entreprise introuvable",
        LOGIN_SUCCESSFULL: "Connexion réussie",
        Email_NOT_VERIFIED: "L'adresse e-mail de l'hôte n'est pas vérifiée",
        EMAIL_ALREADY_EXISTS: "Cet adresse e-mail existe déjà",
        PHONE_ALREADY_EXISTS: "Ce numéro de téléphone existe déjà",
        SIGNUP_SUCCESSFULLY: "Inscription réussie, un code à usage unique a été envoyé à votre numéro de mobile",
        OTP_SENT_SUCCESSFULLY: "Le code à usage unique à été envoyé avec succès",
        OTP_INVALID: "Code à usage unique invalide",
        URL_INVALID: "URL invalide",
        OTP_VERIFIED: "Le code à usage unique a été vérifié avec succès",
        OTP_EXPIRED: "Le code à usage unique à expiré",
        INCORRECT_PASSWORD: "Le mot de passe est incorrect",
        LOGIN_SUCCESSFULLY: "Connexion utilisateur réussie",
        ALREADY_BLOCKED: "L'hôte est déjà bloqué",
        USER_BLOCKED_SUCCESSFULLY: "L’hôte a été bloqué avec succès",
        USER_ALREADY_ACTIVE: "L'hôte est déjà actif",
        USER_UNBLOCKED_SUCCESSFULLY: "L'hôte a été débloqué avec succès",
        USER_ALREADY_DELETED: "L'hôte a déjà été supprimé",
        USER_DELETED_SUCCESSFULLY: "L'hôte a été supprimé avec succès",
        USER_VERIFIED_SUCCESSFULLY: "L'hôte a été vérifié avec succès",
        USER_ALREADY_VERIFIED: "L'hôte est déjà vérifié",
        USER_IS_BLOCKED: "Votre compte est bloqué par l'administrateur",
        PROFILE_UPDATED: "La profil a été mis à jour avec succès",
        COMPANY_DETAILS_SAVED: "Les informations de votre entreprise ont été enregistrées avec succès",
        COMPANY_DETAILS: "Réussi",
        COMPANY_DETAILS_UPDATED: "Les informations de votre entreprise ont été mises à jour avec succès.",
        PROPERTY_SPACE_ADDED: "Espace de bien ajouté avec succès",
        DUPLICATE_SPACE_ID: "Identifiant d'espace en double trouvé",
        ACCOUNT_BLOCKED: "Votre compte a été temporairement bloqué",
        PHONE_NOT_MATCHED: "Le numéro de téléphone ne correspond pas",
        PHONE_UPDATED: "Le numéro de téléphone a été mis à jour avec succès",
        COMPANY_ALREADY_EXISTS: "L'entreprise existe déjà",
        STRIPE_NOT_SETUP: "Le compte Stripe n'est pas configuré",
        NO_PAYOUT_AMOUNT : 'Amount is too small'
    },
    de: {
            NOT_FOUND: "Host wurde nicht gefunden.",
            NO_STATE_DATA: 'Zugang verweigert.',
            COMPANY_NOT_FOUND: "Unternehmen wurde nicht gefunden",
            LOGIN_SUCCESSFULL: "Login erfolgreich",
            Email_NOT_VERIFIED: "E-Mail Adresse ist noch nicht verifiziert!",
            EMAIL_ALREADY_EXISTS: "Ein Konto mit dieser E-Mail exestiert bereits.",
            PHONE_ALREADY_EXISTS: "Ein Konto mit dieser Telefonnummer exestiert bereits.",
            SIGNUP_SUCCESSFULLY: "Anmeldung erfolgreich! Ein einmaliger Verifizierungscode wurde an dein Telefon gesendet.",
            OTP_SENT_SUCCESSFULLY: "Wir haben den Verifizierungscode erfolgreich an dein Telefon gesendet.",
            OTP_INVALID: "Ungültiger OTP",
            URL_INVALID: "Ungültige URL",
            OTP_VERIFIED: "OTP erfolgreich bestätigt",
            OTP_EXPIRED: "OTP abgelaufen",
            INCORRECT_PASSWORD: "Das Passwort ist falsch.",
            LOGIN_SUCCESSFULLY: "Erfolgreiche Anmeldung",
            ALREADY_BLOCKED: "Host ist bereits blockiert.",
            USER_BLOCKED_SUCCESSFULLY: "Host erfolgreich geblockt.",
            USER_ALREADY_ACTIVE: "Host ist bereits aktiv.",
            USER_UNBLOCKED_SUCCESSFULLY: "Host erfolgreich entblockt!",
            USER_ALREADY_DELETED: "Host wurde bereits gelöscht",
            USER_DELETED_SUCCESSFULLY: "Host erfolgreich gelöscht",
            USER_VERIFIED_SUCCESSFULLY: "Host erfolgreich verifiziert!",
            USER_ALREADY_VERIFIED: "Host ist bereits verifiziert!",
            USER_IS_BLOCKED: "Dein Account wurde geblockt. Bitte wende dich an happy@desk-now.com, um ein Support Ticket zu eröffnen.",
            PROFILE_UPDATED: "Profil erfoglreich aktualisiert!",
            COMPANY_DETAILS_SAVED: "Deine Unternehmensinformationen wurden erfolgreich aktualisiert.",
            COMPANY_DETAILS: "Das hat geklappt!",
            COMPANY_DETAILS_UPDATED: "Deine Unternehmensinformationen wurden erfolgreich aktualisiert.",
            PROPERTY_SPACE_ADDED: "Arbeitsplatz wurde erfolgreich hinzugefügt!",
            DUPLICATE_SPACE_ID: "Doppelte Platz ID gefunden",
            DUPLICATE_PRICING: "Doppelte Bepreisung gefunden",
            ACCOUNT_BLOCKED: "Dein Account wurde zeitweise geblockt. Bitte wende dich an happy@desk-now, um ein Support Ticket zu eröffnen",
            PHONE_NOT_MATCHED: "Telefonnummer stimmt nicht überein",
            PHONE_UPDATED: "Telefonnummer wurde erfolgreich aktualisiert!",
            COMPANY_ALREADY_EXISTS: "Unternehmen exestiert bereits",
            STRIPE_NOT_SETUP: 'Stripe Account ist nicht für Zahlungen eingerichtet',
            DUPLICATE_PARTNER: 'Partner ist bereits einem anderen Standort zugewiesen', //new 
            DUPLICATE_EMPLOYEE: 'Doppelte Mitarbeiter gewählt',
            UNITS_NOT_AVAILABLE: 'Einheiten nicht verfügbar',
            NOT_ALLOWED: 'Partner nicht berechtigt.',
            NO_PAYOUT_AMOUNT : 'Betrag ist zu gering'
    },
    it: {
        DUPLICATE_PARTNER: 'Partner already associated with another property', //new 
        DUPLICATE_EMPLOYEE: 'Duplicate employee selected',
        UNITS_NOT_AVAILABLE: 'Units Not Available',
        NOT_ALLOWED: 'Partner not allowed',
        NOT_FOUND: "Host non trovato",
        NO_STATE_DATA: "Accesso negato.",
        COMPANY_NOT_FOUND: "Azienda non trovata",
        LOGIN_SUCCESSFULL: "Accesso effettuato con successo",
        Email_NOT_VERIFIED: "L'e-mail dell'host non è stata verificata",
        EMAIL_ALREADY_EXISTS: "Questa e-mail esiste già",
        PHONE_ALREADY_EXISTS: "Questo numero di telefono esiste già",
        SIGNUP_SUCCESSFULLY: "Registrazione effettuata con successo. L'OTP è stato inviato al tuo numero di cellulare",
        OTP_SENT_SUCCESSFULLY: "L'OTP è stato inviato con successo",
        OTP_INVALID: "OTP non valido",
        URL_INVALID: "URL non valido",
        OTP_VERIFIED: "OTP verificato con successo",
        OTP_EXPIRED: "OTP scaduto",
        INCORRECT_PASSWORD: "La password non è corretta",
        LOGIN_SUCCESSFULLY: "Accesso utente avvenuto con successo",
        ALREADY_BLOCKED: "L'host è già bloccato",
        USER_BLOCKED_SUCCESSFULLY: "Host bloccato con successo",
        USER_ALREADY_ACTIVE: "L'host è già attivo",
        USER_UNBLOCKED_SUCCESSFULLY: "Host sbloccato con successo",
        USER_ALREADY_DELETED: "Host già eliminato",
        USER_DELETED_SUCCESSFULLY: "Host eliminato con successo",
        USER_VERIFIED_SUCCESSFULLY: "Host verificato con successo",
        USER_ALREADY_VERIFIED: "Host già verificato",
        USER_IS_BLOCKED: "Il tuo account è bloccato dall'amministratore",
        PROFILE_UPDATED: "Il profilo è stato aggiornato con successo",
        COMPANY_DETAILS_SAVED: "I dettagli della tua azienda sono stati salvati con successo",
        COMPANY_DETAILS: "Con successo",
        COMPANY_DETAILS_UPDATED: "I dettagli della tua azienda sono stati aggiornati con successo.",
        PROPERTY_SPACE_ADDED: "Spazio proprietà aggiunto con successo",
        DUPLICATE_SPACE_ID: "Trovato ID spazio duplicato",
        ACCOUNT_BLOCKED: "Il tuo account è stato bloccato temporaneamente",
        PHONE_NOT_MATCHED: "Numero di telefono non corrispondente",
        PHONE_UPDATED: "Numero di telefono aggiornato con successo",
        COMPANY_ALREADY_EXISTS: "L'azienda esiste già",
        STRIPE_NOT_SETUP: "Account Stripe non configurato",
        NO_PAYOUT_AMOUNT : 'Amount is too small'
    },
    pl: {
        
        DUPLICATE_PARTNER: 'Partner already associated with another property', //new 
        DUPLICATE_EMPLOYEE: 'Duplicate employee selected',
        UNITS_NOT_AVAILABLE: 'Units Not Available',
        NOT_ALLOWED: 'Partner not allowed',
        NOT_FOUND: "Nie odnaleziono serwera",
        NO_STATE_DATA: "Odmowa dostępu.",
        COMPANY_NOT_FOUND: "Firma nie została odnaleziona",
        LOGIN_SUCCESSFULL: "Zalogowanie powiodło się",
        Email_NOT_VERIFIED: "Adres e-mail gospodarza nie został zweryfikowany",
        EMAIL_ALREADY_EXISTS: "Ten adres e-mail już istnieje",
        PHONE_ALREADY_EXISTS: "Ten numer telefonu już istnieje.",
        SIGNUP_SUCCESSFULLY: "Rejestracja powiodła się, hasło jednorazowe zostało wysłane na Twój numer telefonu komórkowego",
        OTP_SENT_SUCCESSFULLY: "Hasło jednorazowe zostało pomyślnie wysłane",
        OTP_INVALID: "Nieprawidłowe hasło jednorazowe",
        URL_INVALID: "Nieprawidłowy adres URL",
        OTP_VERIFIED: "Hasło jednorazowe zostało pomyślnie zweryfikowane",
        OTP_EXPIRED: "Hasło jednorazowe wygasło",
        INCORRECT_PASSWORD: "Hasło jest nieprawidłowe",
        LOGIN_SUCCESSFULLY: "Użytkownik zalogował się pomyślnie",
        ALREADY_BLOCKED: "Gospodarz jest już zablokowany",
        USER_BLOCKED_SUCCESSFULLY: "Gospodarz został pomyślnie zablokowany",
        USER_ALREADY_ACTIVE: "Gospodarz jest już aktywny",
        USER_UNBLOCKED_SUCCESSFULLY: "Gospodarz został pomyślnie odblokowany",
        USER_ALREADY_DELETED: "Gospodarz został już usunięty",
        USER_DELETED_SUCCESSFULLY: "Gospodarz został pomyślnie usunięty",
        USER_VERIFIED_SUCCESSFULLY: "Gospodarz został pomyślnie zweryfikowany",
        USER_ALREADY_VERIFIED: "Gospodarz jest już zweryfikowany",
        USER_IS_BLOCKED: "Twoje konto zostało zablokowane przez administratora",
        PROFILE_UPDATED: "Profil został pomyślnie zaktualizowany",
        COMPANY_DETAILS_SAVED: "Dane Twojej firmy zostały pomyślnie zapisane",
        COMPANY_DETAILS: "Zakończono sukcesem",
        COMPANY_DETAILS_UPDATED: "Dane Twojej firmy zostały pomyślnie zaktualizowane.",
        PROPERTY_SPACE_ADDED: "Miejsce w obiekcie zostało pomyślnie dodane",
        DUPLICATE_SPACE_ID: "Znaleziono zdublowany identyfikator miejsca",
        ACCOUNT_BLOCKED: "Twoje konto zostało tymczasowo zablokowane",
        PHONE_NOT_MATCHED: "Nie zgadza się numer telefonu",
        PHONE_UPDATED: "Numer telefonu został pomyślnie zaktualizowany",
        COMPANY_ALREADY_EXISTS: "Nazwa firmy już istnieje",
        STRIPE_NOT_SETUP: "Konto Stripe nie zostało skonfigurowane",
        NO_PAYOUT_AMOUNT : 'Amount is too small'
    },
    ro: {
        DUPLICATE_PARTNER: 'Partner already associated with another property', //new 
        DUPLICATE_EMPLOYEE: 'Duplicate employee selected',
        UNITS_NOT_AVAILABLE: 'Units Not Available',
        NOT_ALLOWED: 'Partner not allowed',
        NOT_FOUND: "Gazda nu a fost găsită",
        NO_STATE_DATA: "Acces refuzat.",
        COMPANY_NOT_FOUND: "Compania nu a fost găsită",
        LOGIN_SUCCESSFULL: "Autentificare cu succes",
        Email_NOT_VERIFIED: "Adresă de e-mail de gazdă neverificată",
        EMAIL_ALREADY_EXISTS: "Această adresă de e-mail este deja înregistrată",
        PHONE_ALREADY_EXISTS: "Acest număr de telefon este deja înregistrat",
        SIGNUP_SUCCESSFULLY: "Înregistrare reușită, parola unică a fost trimisă la numărul dvs. de mobil",
        OTP_SENT_SUCCESSFULLY: "OTP trimis cu succes",
        OTP_INVALID: "OTP incorect",
        URL_INVALID: "URL nevalid",
        OTP_VERIFIED: "OTP verificat cu succes",
        OTP_EXPIRED: "OTP expirat",
        INCORRECT_PASSWORD: "Parolă incorectă",
        LOGIN_SUCCESSFULLY: "Autentificare utilizator reușită",
        ALREADY_BLOCKED: "Gazda este deja blocată",
        USER_BLOCKED_SUCCESSFULLY: "Gazda a fost blocată cu succes",
        USER_ALREADY_ACTIVE: "Gazda este deja activă",
        USER_UNBLOCKED_SUCCESSFULLY: "Gazdă deblocată cu succes",
        USER_ALREADY_DELETED: "Gazdă deja ștersă",
        USER_DELETED_SUCCESSFULLY: "Gazdă ștearsă cu succes",
        USER_VERIFIED_SUCCESSFULLY: "Gazdă verificată cu succes",
        USER_ALREADY_VERIFIED: "Gazdă deja verificată",
        USER_IS_BLOCKED: "Contul dvs. este blocat de administrator",
        PROFILE_UPDATED: "Profil actualizat cu succes",
        COMPANY_DETAILS_SAVED: "Detaliile companiei dvs. au fost salvate cu succes",
        COMPANY_DETAILS: "Reușit",
        COMPANY_DETAILS_UPDATED: "Detaliile companiei dvs. au fost actualizate cu succes.",
        PROPERTY_SPACE_ADDED: "Proprietate adăugată cu succes",
        DUPLICATE_SPACE_ID: "S-a depistat un ID spațiu duplicat",
        ACCOUNT_BLOCKED: "Contul dvs. a fost blocat temporar",
        PHONE_NOT_MATCHED: "Numărul de telefon nu se potrivește",
        PHONE_UPDATED: "Numărul de telefon a fost actualizat cu succes",
        COMPANY_ALREADY_EXISTS: "Compania există deja",
        STRIPE_NOT_SETUP: "Contul Stripe nu este configurat",
        NO_PAYOUT_AMOUNT : 'Amount is too small'
    },
    ru: {
        DUPLICATE_PARTNER: 'Partner already associated with another property', //new 
        DUPLICATE_EMPLOYEE: 'Duplicate employee selected',
        UNITS_NOT_AVAILABLE: 'Units Not Available',
        NOT_ALLOWED: 'Partner not allowed',
        NOT_FOUND: "Владелец не найден",
        NO_STATE_DATA: "Доступ запрещен.",
        COMPANY_NOT_FOUND: "Компания не найдена",
        LOGIN_SUCCESSFULL: "Вход выполнен",
        Email_NOT_VERIFIED: "Электронная почта владельца не проверена",
        EMAIL_ALREADY_EXISTS: "Этот адрес электронной почты уже существует",
        PHONE_ALREADY_EXISTS: "Этот номер телефона уже существует",
        SIGNUP_SUCCESSFULLY: "Регистрация прошла успешно: одноразовый пароль отправлен на ваш номер телефона",
        OTP_SENT_SUCCESSFULLY: "Одноразовый пароль отправлен",
        OTP_INVALID: "Недействительный одноразовый пароль",
        URL_INVALID: "Недействительный URL-адрес",
        OTP_VERIFIED: "Одноразовый пароль подтвержден",
        OTP_EXPIRED: "Срок действия одноразового пароля истек",
        INCORRECT_PASSWORD: "Неверный пароль",
        LOGIN_SUCCESSFULLY: "Вход пользователя выполнен",
        ALREADY_BLOCKED: "Владелец уже заблокирован",
        USER_BLOCKED_SUCCESSFULLY: "Владелец заблокирован",
        USER_ALREADY_ACTIVE: "Владелец уже активен",
        USER_UNBLOCKED_SUCCESSFULLY: "Владелец разблокирован",
        USER_ALREADY_DELETED: "Владелец уже удален",
        USER_DELETED_SUCCESSFULLY: "Владелец удален",
        USER_VERIFIED_SUCCESSFULLY: "Проверка владельца осуществлена",
        USER_ALREADY_VERIFIED: "Проверка владельца уже осуществлена",
        USER_IS_BLOCKED: "Ваша учетная запись заблокирована администратором",
        PROFILE_UPDATED: "Ваш профиль обновлен",
        COMPANY_DETAILS_SAVED: "Информация о вашей компании сохранена",
        COMPANY_DETAILS: "Готово",
        COMPANY_DETAILS_UPDATED: "Информация о вашей компании обновлена.",
        PROPERTY_SPACE_ADDED: "Помещение объекта добавлено",
        DUPLICATE_SPACE_ID: "Обнаружен дубликат идентификатора помещения",
        ACCOUNT_BLOCKED: "Ваш аккаунт временно заблокирован",
        PHONE_NOT_MATCHED: "Номера телефона не сопадают",
        PHONE_UPDATED: "Номер телефона обновлен",
        COMPANY_ALREADY_EXISTS: "Компания уже существует",
        STRIPE_NOT_SETUP: "Учетная запись Stripe не настроена",
        NO_PAYOUT_AMOUNT : 'Amount is too small'
    },
    es: {
        DUPLICATE_PARTNER: 'Partner already associated with another property', //new 
        DUPLICATE_EMPLOYEE: 'Duplicate employee selected',
        UNITS_NOT_AVAILABLE: 'Units Not Available',
        NOT_ALLOWED: 'Partner not allowed',
        NOT_FOUND: "Anfitrión no encontrado",
        NO_STATE_DATA: "Acesso denegado.",
        COMPANY_NOT_FOUND: "Compañía no encontrada",
        LOGIN_SUCCESSFULL: "Sesión iniciada correctamente",
        Email_NOT_VERIFIED: "El correo electrónico del anfitrión no está verificado",
        EMAIL_ALREADY_EXISTS: "Este correo ya existe",
        PHONE_ALREADY_EXISTS: "Este número de teléfono ya existe",
        "SIGNUP_SUCCESSFULLY": "Registro completado correctamente; la contraseña de un solo uso se ha enviado a tu número de teléfono",
        OTP_SENT_SUCCESSFULLY: "El código OTP se ha enviado correctamente",
        OTP_INVALID: "Codigo OTP no válido",
        URL_INVALID: "URL no válida",
        OTP_VERIFIED: "El código OTP we ha verificado correctamente",
        OTP_EXPIRED: "El código OTP ha caducado",
        INCORRECT_PASSWORD: "La contraseña es incorrecta",
        LOGIN_SUCCESSFULLY: "Sesión de usuario iniciada correctamente",
        ALREADY_BLOCKED: "El anfitrión ya está bloqueado",
        USER_BLOCKED_SUCCESSFULLY: "El anfitrión se ha bloqueado correctamente",
        USER_ALREADY_ACTIVE: "El host ya está activo",
        USER_UNBLOCKED_SUCCESSFULLY: "El anfitrión se ha desbloqueado correctamente",
        USER_ALREADY_DELETED: "El anfitrión ya ha sido eliminado",
        USER_DELETED_SUCCESSFULLY: "El anfitrión se ha eliminado correctamente",
        USER_VERIFIED_SUCCESSFULLY: "El anfitrión se ha verificado correctamente",
        USER_ALREADY_VERIFIED: "El anfitrión ya ha sido verificado",
        USER_IS_BLOCKED: "Tu cuenta está bloqueada por el administrador",
        PROFILE_UPDATED: "Tu perfil se ha actualizado correctamente",
        COMPANY_DETAILS_SAVED: "Los datos de tu empresa se han guardado correctamente",
        COMPANY_DETAILS: "Correctamente",
        COMPANY_DETAILS_UPDATED: "Los datos de tu empresa se han actualizado correctamente.",
        PROPERTY_SPACE_ADDED: "El espacio de la propiedad se ha añadido correctamente",
        DUPLICATE_SPACE_ID: "Se ha encontrado un ID de espacio duplicado",
        ACCOUNT_BLOCKED: "Tu cuenta ha sido bloqueada temporalmente",
        PHONE_NOT_MATCHED: "El número de teléfono no coincide",
        PHONE_UPDATED: "El número de teléfono se ha actualizado correctamente",
        COMPANY_ALREADY_EXISTS: "La compañía ya existe",
        STRIPE_NOT_SETUP: "La cuenta de Stripe no está configurada",
        NO_PAYOUT_AMOUNT : 'Amount is too small'
    },
    tr: {
        DUPLICATE_PARTNER: 'Partner already associated with another property', //new 
        DUPLICATE_EMPLOYEE: 'Duplicate employee selected',
        UNITS_NOT_AVAILABLE: 'Units Not Available',
        NOT_ALLOWED: 'Partner not allowed',
        NOT_FOUND: "Mekân sunucu bulunamadı",
        NO_STATE_DATA: "Erişim Reddedildi.",
        COMPANY_NOT_FOUND: "Şirket bulunamadı",
        LOGIN_SUCCESSFULL: "Giriş yapın",
        Email_NOT_VERIFIED: "Sunucu e-postası doğrulanmadı",
        EMAIL_ALREADY_EXISTS: "Bu e-posta zaten var",
        PHONE_ALREADY_EXISTS: "Bu telefon numarası zaten var",
        SIGNUP_SUCCESSFULLY: "Kaydınızı tamamlayın. Mobil numaranıza tek kullanımlık parola (OTP) gönderildi",
        OTP_SENT_SUCCESSFULLY: "OTP gönderme işlemi tamam",
        OTP_INVALID: "Geçersiz OTP",
        URL_INVALID: "Geçersiz URL",
        OTP_VERIFIED: "OTP doğrulama tamam",
        OTP_EXPIRED: "OTP'nin süresi doldu",
        INCORRECT_PASSWORD: "Parola yanlış",
        LOGIN_SUCCESSFULLY: "Kullanıcı girişi tamam",
        ALREADY_BLOCKED: "Mekân sunucu zaten engellenmiş",
        USER_BLOCKED_SUCCESSFULLY: "Mekân sunucu engellenmiştir",
        USER_ALREADY_ACTIVE: "Mekân sunucu zaten etkin",
        USER_UNBLOCKED_SUCCESSFULLY: "Mekân sunucunun engeli kaldırılmıştır",
        USER_ALREADY_DELETED: "Mekân sunucu zaten silinmiş",
        USER_DELETED_SUCCESSFULLY: "Mekân sunucu silinmiştir",
        USER_VERIFIED_SUCCESSFULLY: "Mekân sunucu doğrulanmıştır",
        USER_ALREADY_VERIFIED: "Mekân sunucu zaten doğrulanmış",
        USER_IS_BLOCKED: "Hesabınız yönetici tarafından engellendi",
        PROFILE_UPDATED: "Profil güncelleme tamam",
        COMPANY_DETAILS_SAVED: "Şirket bilgileriniz kaydedilmiştir",
        COMPANY_DETAILS: "Tamamlandı",
        COMPANY_DETAILS_UPDATED: "Şirket bilgileriniz başarıyla güncellenmiştir.",
        PROPERTY_SPACE_ADDED: "Mekân ekleme tamam",
        DUPLICATE_SPACE_ID: "Mükerrer mekân no. bulundu",
        ACCOUNT_BLOCKED: "Hesabınız geçici olarak bloke edilmiştir.",
        PHONE_NOT_MATCHED: "Telefon numarası eşleşmiyor",
        PHONE_UPDATED: "Telefon numarası güncellenmiştir",
        COMPANY_ALREADY_EXISTS: "Şirket zaten var",
        STRIPE_NOT_SETUP: "Stripe hesabı kurulmamış",
        NO_PAYOUT_AMOUNT : 'Amount is too small'
    }
};

export default (lang: string, data?: any) => ({
    LOGIN_SUCCESSFULL: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].LOGIN_SUCCESSFULL },
    USER_CREATED_SUCCEFULLY: { httpCode: HTTP.SUCCESS, statusCode: 201, message: MSG[lang].LOGIN_SUCCESSFULL },
    NOT_FOUND: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].NOT_FOUND },
    NO_PAYOUT_AMOUNT: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].NO_PAYOUT_AMOUNT },
    COMPANY_NOT_FOUND: { httpCode: HTTP.BAD_REQUEST, statusCode: 417, message: MSG[lang].COMPANY_NOT_FOUND },
    COMPANY_NOT_FOUND_USER: { httpCode: HTTP.NO_CONTENT, statusCode: 204, message: MSG[lang].COMPANY_NOT_FOUND },
    Email_NOT_VERIFIED: { httpCode: HTTP.NOT_VERIFIED, statusCode: 410, message: MSG[lang].Email_NOT_VERIFIED },
    PHONE_ALREADY_EXISTS: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].PHONE_ALREADY_EXISTS },
    EMAIL_ALREADY_EXISTS: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].EMAIL_ALREADY_EXISTS },
    SIGNUP_SUCCESSFULLY: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].SIGNUP_SUCCESSFULLY },
    LOGIN_SUCCESSFULLY: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].LOGIN_SUCCESSFULLY },
    OTP_SENT_SUCCESSFULLY: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].OTP_SENT_SUCCESSFULLY },
    OTP_INVALID: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].OTP_INVALID },
    URL_INVALID: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].URL_INVALID },
    OTP_EXPIRED: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].OTP_EXPIRED },
    OTP_VERIFIED: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].OTP_VERIFIED },
    INCORRECT_PASSWORD: { httpCode: HTTP.BAD_REQUEST, statusCode: 413, message: MSG[lang].INCORRECT_PASSWORD },
    USER_BLOCKED_SUCCESSFULLY: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].USER_BLOCKED_SUCCESSFULLY },
    ALREADY_BLOCKED: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].ALREADY_BLOCKED },
    DUPLICATE_SPACE_ID: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].DUPLICATE_SPACE_ID },
    DUPLICATE_PRICING: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].DUPLICATE_PRICING },
    COMPANY_ALREADY_EXISTS: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].COMPANY_ALREADY_EXISTS },
    USER_UNBLOCKED_SUCCESSFULLY: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].USER_UNBLOCKED_SUCCESSFULLY },
    USER_ALREADY_ACTIVE: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].USER_ALREADY_ACTIVE },
    USER_ALREADY_DELETED: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].USER_ALREADY_DELETED },
    USER_DELETED_SUCCESSFULLY: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].USER_DELETED_SUCCESSFULLY },
    USER_VERIFIED_SUCCESSFULLY: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].USER_VERIFIED_SUCCESSFULLY },
    USER_ALREADY_VERIFIED: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].USER_ALREADY_VERIFIED },
    USER_IS_BLOCKED: { httpCode: HTTP.ACCOUNT_BLOCKED, statusCode: 409, message: MSG[lang].USER_IS_BLOCKED },
    PROFILE_UPDATED: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].PROFILE_UPDATED },
    COMPANY_DETAILS_SAVED: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].COMPANY_DETAILS_SAVED },
    COMPANY_DETAILS: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].COMPANY_DETAILS },
    COMPANY_DETAILS_UPDATED: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].COMPANY_DETAILS_UPDATED },
    NO_STATE_DATA: { httpCode: HTTP.SUCCESS, statusCode: 211, message: MSG[lang].NO_STATE_DATA },
    PROPERTY_SPACE_ADDED: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].PROPERTY_SPACE_ADDED },
    ACCOUNT_BLOCKED: { httpCode: HTTP.ACCOUNT_BLOCKED, statusCode: 409, message: MSG[lang].ACCOUNT_BLOCKED },
    PHONE_NOT_MATCHED: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].PHONE_NOT_MATCHED },
    PHONE_UPDATED: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].PHONE_UPDATED },
    STRIPE_NOT_SETUP: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].STRIPE_NOT_SETUP },
    DUPLICATE_PARTNER: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].DUPLICATE_PARTNER },
    PARTNER_NOT_ALLOWED: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].NOT_ALLOWED },
    DUPLICATE_EMPLOYEE: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].DUPLICATE_EMPLOYEE },
    UNITS_NOT_AVAILABLE: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].UNITS_NOT_AVAILABLE },

});

export const CUSTOM_SUCCESS = (data?: any, message?: string) => {
    return ({
        httpCode: 200,
        statusCode: 200,
        message: message ? message : "Success",
        data: data ? data : {}
    })
}

export const CUSTOM_ERROR = (data?: any, message?: string) => {
    return ({
        httpCode: 400,
        statusCode: 400,
        message: message ? message : "Success",
        data: data ? data : {}
    })
}