/**
 * @name content.response
 * @description defines response for content entity
 * @created 2019-08-27 15:34:43
 * @author Desk Now Dev Team
 * @meta Response Code: 80XX
*/

import HTTP from "./code.response";

export const MSG: any = {
    en: {
        PRICE_TOO_LOW: 'Price must be larger than or equal to 1',
        NOT_FOUND: "Property not found",
        NOT_AUTHRIZED: "You are not authorized to update this property",
        NOT_VERIFIED: "Your account is not yet verified by admin.",
        NOT_ALLOWED: "You are not authorized to add this property, verification pending from the Admin",
        INCOMPLETE_FLOOR_DETAILS: "You are not allowed to publish property with incomplete floor details!",
        PROPERTY_UPDATED: "Property updated successfully",
        PROPERTY_SAVED: "Property saved successfully",
        PROPERTY_DELETED_SUCCESSFULLY: "Property deleted successfully",
        SPACE_DELETED_SUCCESSFULLY: "Property deleted successfully",
        PROPERTY_ACTIVATED: "Property activated",
        PROPERTY_ALREADY_ACTIVE: "Property already active",
        PROPERTY_DE_ACTIVATED: "Property deactivated",
        COHOST_DE_ACTIVATED: "Cohost account deactivated successfully",
        COHOST_ACTIVATED: "Cohost account activated successfully",
        PROPERTY_ALREADY_DE_ACTIVE: "Property already deactivated",
        ALREADY_ADDED: "City already added",
        INVALID_CART: "Empty cart please add space",
        USER_NOT_FOUND: "No user found can not proceed booking",
        BOOKING_NOT_FOUND: "Booking not found",
        BOOKING_ACCEPTED: "Booking Accepted",
        BOOKING_REJECT: "Booking Rejected",
        WISHLIST_USER: "Please login as a user to avail this functionality",
        NO_UNITS_AVAILABLE: `Max quantity limit reached, can not add more units!`,
        NO_SPACE_AVAILABLE: `No more space units available for selected time period.`,
        COHOST_DELETED: 'Cohost deleted successfully',
        INVALID_REDEMPTION_CODE: `The gift card you entered is not valid.`,
        ALREADY_REDEEMED: `The gift card has already been redeemed.`,
        DUPLICATE_HOLIDAY_DATE: 'Date already exist please select another date',
        OFFLINE_BOOKING_FOUND: `No online booking found!`,
        NO_SLOTS_AVAILABLE: `Unfortunately,selected slot is not available!`,
        NO_PRICE_AVAILABLE: 'Price not available!',
        INCOMPLETE_PROFILE: `Your profile/company details are incomplete.Please complete !`,
        INVALID_BOOKING_ID: `Invalid bookingId`,
        //new
        PROPERTY_CLAIMED_RQUEST: 'Request successfully send to admin',
        PROPERTY_CLAMIED_ERROR: 'Cannot claimed the property',
        BAD_EMPLOYEE_REQUEST: `Hey! You cannot perform this action since these units are already distributed between partners and to continue to perform this action, please update the units assigned to your partners first`,
        PROPERTY_NOT_ACTIVE : 'Property is not active!'
    },
    cs: {
        PRICE_TOO_LOW: 'Price must be larger than or equal to 1',
        INCOMPLETE_PROFILE: `Your profile/company details are incomplete.Please complete !`,
        INCOMPLETE_FLOOR_DETAILS: "You are not allowed to publish property with incomplete floor details!",
        NOT_FOUND: "Nemovitost nebyla nalezena",
        NOT_AUTHRIZED: "Nemáte oprávnění aktualizovat tuto nemovitost",
        NOT_VERIFIED: "Váš účet nebyl dosud ověřen správcem.",
        NOT_ALLOWED: "Nemáte oprávnění přidat tuto nemovitost",
        PROPERTY_UPDATED: "Nemovitost byla úspěšně aktualizována",
        PROPERTY_SAVED: "Nemovitost byla úspěšně uložena",
        PROPERTY_DELETED_SUCCESSFULLY: "Nemovitost byla úspěšně smazána",
        SPACE_DELETED_SUCCESSFULLY: "Nemovitost byla úspěšně smazána",
        PROPERTY_ACTIVATED: "Nemovitost byla aktivována",
        PROPERTY_ALREADY_ACTIVE: "Nemovitost je již aktivní",
        PROPERTY_DE_ACTIVATED: "Nemovitost byla deaktivována",
        COHOST_DE_ACTIVATED: "Účet spoluhostitele byl úspěšně deaktivován",
        COHOST_ACTIVATED: "Účet spoluhostitele byl úspěšně aktivován",
        PROPERTY_ALREADY_DE_ACTIVE: "Nemovitost již byla deaktivována",
        ALREADY_ADDED: "Město již bylo přidáno",
        INVALID_CART: "Prázdný košík, přidejte prostor",
        USER_NOT_FOUND: "Nebyl nalezen žádný uživatel, nelze pokračovat v rezervaci",
        BOOKING_NOT_FOUND: "Rezervace nebyla nalezena",
        BOOKING_ACCEPTED: "Rezervace byla přijata",
        BOOKING_REJECT: "Rezervace byla odmítnuta",
        WISHLIST_USER: "Pro využití této funkce se přihlaste jako uživatel",
        NO_UNITS_AVAILABLE: "Bohužel! Žádné zbývající jednotky",
        NO_SPACE_AVAILABLE: "Pro zvolené časové období nejsou k dispozici žádné další jednotky.",
        COHOST_DELETED: "Spoluhostitel byl úspěšně smazán",
        INVALID_REDEMPTION_CODE: "Zadaná dárková karta je neplatná.",
        ALREADY_REDEEMED: "Dárková karta již byla uplatněna.",
        DUPLICATE_HOLIDAY_DATE: "Datum již existuje, vyberte jiné datum",
        OFFLINE_BOOKING_FOUND: "Nebyla nalezena žádná online rezervace!",
        NO_SLOTS_AVAILABLE: 'Vybrané místo bohužel není k dispozici!',
        NO_PRICE_AVAILABLE: 'Cena není k dispozici!',
        //new
        BAD_EMPLOYEE_REQUEST: `Hey! You cannot perform this action since these units are already distributed between partners and to continue to perform this action, please update the units assigned to your partners first.`,
        PROPERTY_NOT_ACTIVE : 'Property is not active!'
    },
    nl: {
        PRICE_TOO_LOW: 'Price must be larger than or equal to 1',
        INCOMPLETE_PROFILE: `Your profile/company details are incomplete.Please complete !`,
        INCOMPLETE_FLOOR_DETAILS: "You are not allowed to publish property with incomplete floor details!",
        NOT_FOUND: "Accommodatie niet gevonden",
        NOT_AUTHRIZED: "U bent niet gemachtigd om deze accommodatie bij te werken",
        NOT_VERIFIED: "Uw account is nog niet geverifieerd door beheerder.",
        NOT_ALLOWED: "U bent niet bevoegd om deze accommodatie toe te voegen",
        PROPERTY_UPDATED: "Accommodatie succesvol gewijzigd",
        PROPERTY_SAVED: "Accommodatie succesvol opgeslagen",
        PROPERTY_DELETED_SUCCESSFULLY: "Accommodatie succesvol verwijderd",
        SPACE_DELETED_SUCCESSFULLY: "Accommodatie succesvol verwijderd",
        PROPERTY_ACTIVATED: "Accommodatie geactiveerd",
        PROPERTY_ALREADY_ACTIVE: "Accommodatie al actief",
        PROPERTY_DE_ACTIVATED: "Accommodatie gedeactiveerd",
        COHOST_DE_ACTIVATED: "Cohost-account succesvol gedeactiveerd",
        COHOST_ACTIVATED: "Cohost-account succesvol geactiveerd",
        PROPERTY_ALREADY_DE_ACTIVE: "Accommodatie al gedeactiveerd",
        ALREADY_ADDED: "Stad al toegevoegd",
        INVALID_CART: "Leeg winkelwagentje, voeg space toe",
        USER_NOT_FOUND: "Geen gebruiker gevonden, kan niet doorgaan met boeken",
        BOOKING_NOT_FOUND: "Boeking niet gevonden",
        BOOKING_ACCEPTED: "Boeking geaccepteerd",
        BOOKING_REJECT: "Boeking geweigerd",
        WISHLIST_USER: "Log in als gebruiker om van deze functionaliteit gebruik te maken",
        NO_UNITS_AVAILABLE: "Helaas! Geen eenheden meer over",
        NO_SPACE_AVAILABLE: "Geen space-eenheden meer beschikbaar voor de geselecteerde tijdsperiode.",
        COHOST_DELETED: "Cohost is verwijderd",
        INVALID_REDEMPTION_CODE: "De cadeaubon die je hebt ingevoerd, is niet geldig.",
        ALREADY_REDEEMED: "De cadeaubon is al ingewisseld.",
        DUPLICATE_HOLIDAY_DATE: "Datum bestaat al, selecteer een andere datum",
        OFFLINE_BOOKING_FOUND: "Geen online boeking gevonden!",
        NO_SLOTS_AVAILABLE: 'Helaas is het geselecteerde tijdslot niet beschikbaar!',
        NO_PRICE_AVAILABLE: 'Prijs niet beschikbaar!',
        //new
        BAD_EMPLOYEE_REQUEST: `Hey! You cannot perform this action since these units are already distributed between partners and to continue to perform this action, please update the units assigned to your partners first.`,
        PROPERTY_NOT_ACTIVE : 'Property is not active!'
    },
    fr: {
        PRICE_TOO_LOW: 'Price must be larger than or equal to 1',
        INCOMPLETE_PROFILE: `Your profile/company details are incomplete.Please complete !`,
        INCOMPLETE_FLOOR_DETAILS: "You are not allowed to publish property with incomplete floor details!",
        NOT_FOUND: "Bien introuvable",
        NOT_AUTHRIZED: "Vous n'avez pas l'autorisation de mettre à jour ce bien",
        NOT_VERIFIED: "Votre compte n'est pas encore vérifié par l'administrateur.",
        NOT_ALLOWED: "Vous n'avez pas l'autorisation d'ajouter ce bien",
        PROPERTY_UPDATED: "Bien mis à jour avec succès",
        PROPERTY_SAVED: "Bien enregistré avec succès",
        PROPERTY_DELETED_SUCCESSFULLY: "Bien supprimé avec succès",
        SPACE_DELETED_SUCCESSFULLY: "Bien supprimé avec succès",
        PROPERTY_ACTIVATED: "Bien activé",
        PROPERTY_ALREADY_ACTIVE: "Bien déjà actif",
        PROPERTY_DE_ACTIVATED: "Bien désactivé",
        COHOST_DE_ACTIVATED: "Compte de co-hôte désactivé avec succès",
        COHOST_ACTIVATED: "Compte de co-hôte activé avec succès",
        PROPERTY_ALREADY_DE_ACTIVE: "Bien déjà désactivé",
        ALREADY_ADDED: "Ville déjà ajoutée",
        INVALID_CART: "Panier vide, veuillez ajouter un espace",
        USER_NOT_FOUND: "Aucun utilisateur trouvé, impossible de poursuivre la réservation",
        BOOKING_NOT_FOUND: "Réservation introuvable",
        BOOKING_ACCEPTED: "Réservation acceptée",
        BOOKING_REJECT: "Réservation rejetée",
        WISHLIST_USER: "Veuillez vous connecter en tant qu'utilisateur pour profiter de cette fonctionnalité",
        NO_UNITS_AVAILABLE: "Désolé ! Aucune unité restante",
        NO_SPACE_AVAILABLE: "Aucune unité d'espace disponible pour la période sélectionnée.",
        COHOST_DELETED: "Co-hôte supprimé avec succès",
        INVALID_REDEMPTION_CODE: "La carte-cadeau que vous avez saisie n'est pas valide.",
        ALREADY_REDEEMED: "La carte-cadeau a déjà été utilisée.",
        DUPLICATE_HOLIDAY_DATE: "La date existe déjà, veuillez sélectionner une autre date",
        OFFLINE_BOOKING_FOUND: "Aucune réservation en ligne trouvée !",
        NO_SLOTS_AVAILABLE: "Malheureusement, l'horaire sélectionné n'est pas disponible !",
        NO_PRICE_AVAILABLE: 'Tarif non disponible !',
        //new
        BAD_EMPLOYEE_REQUEST: `Hey! You cannot perform this action since these units are already distributed between partners and to continue to perform this action, please update the units assigned to your partners first.`,
        PROPERTY_NOT_ACTIVE : 'Property is not active!'
    },
    de:{
        PRICE_TOO_LOW: "Der Preis muss höher oder gleich 1 sein",
    NOT_FOUND: "Standort nicht gefunden",
    NOT_AUTHRIZED: "Du bist nicht berechtigt, diesen Standort zu bearbeiten.",
    NOT_VERIFIED: "Dein Konto wurde noch nicht verifiziert oder befindet sich noch in Prüfung.",
    NOT_ALLOWED: "Du bist nicht berechtigt, diesen Standort zu veröffentlichen. Dein Account wird noch auf Echtheit überprüft.",
    INCOMPLETE_FLOOR_DETAILS: "Fehlende Stockwerk Informationen! Wir können diesen Standort nicht veröffentlichen. Bitte überprüfe deine Eingaben.",
    PROPERTY_UPDATED: "Standort wurde erfolgreich aktualisiert",
    PROPERTY_SAVED: "Standort wurde erfolgreich gespeichert",
    PROPERTY_DELETED_SUCCESSFULLY: "Standort wurde gelöscht",
    SPACE_DELETED_SUCCESSFULLY: "Space wurde gelöscht",
    PROPERTY_ACTIVATED: "Standort wurde aktiviert",
    PROPERTY_ALREADY_ACTIVE: "Standort ist bereits aktiviert",
    PROPERTY_DE_ACTIVATED: "Standort deaktiviert",
    COHOST_DE_ACTIVATED: "Benutzer wurde deaktiviert.",
    COHOST_ACTIVATED: "Benutzer wurde aktiviert.",
    PROPERTY_ALREADY_DE_ACTIVE: "Standort ist bereits aktiv.",
    ALREADY_ADDED: "Stadt wurde bereits hinzugefügt.",
    INVALID_CART: "Bitte füge einen Space hinzu",
    USER_NOT_FOUND: "Kein Nutzer gefunden. Wir können die Buchung nicht vervollständigen.",
    BOOKING_NOT_FOUND: "Buchung nicht gefunden",
    BOOKING_ACCEPTED: "Buchung angenommen",
    BOOKING_REJECT: "Buchung abgelehnt",
    WISHLIST_USER: "Bitte logge dich ein, um diese Funktion zu nutzen!",
    NO_UNITS_AVAILABLE: "Die Maximale Anzahl an Einheiten wurde erreicht.",
    NO_SPACE_AVAILABLE: "Für diesen Zeitraum sind keine weiteren Einheiten verfügbar.",
    COHOST_DELETED: "Benutzer wurde erfolgreich gelöscht.",
    INVALID_REDEMPTION_CODE: "Der Gutscheincode ist nicht gültig.",
    ALREADY_REDEEMED: "Der Gutscheincode wurde bereits eingelöst",
    DUPLICATE_HOLIDAY_DATE: "Datum ist bereits eingetragen. Bitte ändere den Zeitraum",
    OFFLINE_BOOKING_FOUND: "Keine online Buchungen gefunden.",
    NO_SLOTS_AVAILABLE: "Leider, ist der gewählte Platz nicht verfügbar",
    NO_PRICE_AVAILABLE: "Preis ist nicht verfügbar",
    INCOMPLETE_PROFILE: "Deine Unternehmensinformationen sind Unvollständig. Bitte vervollständige dein Konto, um fortzufahren.",
    INVALID_BOOKING_ID: "Ungültige Buchungs ID",
    PROPERTY_CLAIMED_RQUEST: 'Request successfully send to admin',
    PROPERTY_CLAMIED_ERROR: "Beanspruchung des Standortes nicht möglich!",
    BAD_EMPLOYEE_REQUEST: "Hey! Das ist leider nicht möglich. Bitte aktualisiere die Verfügbaren Plätze deiner Partner Abteilungen und Standorte, um fortzufahren.",
    PROPERTY_NOT_ACTIVE: "Standort ist nicht aktiv"},
    it: {
        PRICE_TOO_LOW: 'Price must be larger than or equal to 1',
        INCOMPLETE_PROFILE: `Your profile/company details are incomplete.Please complete !`,
        INCOMPLETE_FLOOR_DETAILS: "You are not allowed to publish property with incomplete floor details!",
        NOT_FOUND: "Proprietà non trovata",
        NOT_AUTHRIZED: "Non sei autorizzato ad aggiornare questa proprietà",
        NOT_VERIFIED: "Il tuo account non è stato ancora verificato dall'amministratore.",
        NOT_ALLOWED: "Non sei autorizzato a modificare questa proprietà",
        PROPERTY_UPDATED: "Proprietà aggiornata con successo",
        PROPERTY_SAVED: "Proprietà salvata con successo",
        PROPERTY_DELETED_SUCCESSFULLY: "Proprietà eliminata con successo",
        SPACE_DELETED_SUCCESSFULLY: "Proprietà eliminata con successo",
        PROPERTY_ACTIVATED: "Proprietà attivata",
        PROPERTY_ALREADY_ACTIVE: "Proprietà già attiva",
        PROPERTY_DE_ACTIVATED: "Proprietà disattivata",
        COHOST_DE_ACTIVATED: "Account co-host disattivato con successo",
        COHOST_ACTIVATED: "Account co-host attivato con successo",
        PROPERTY_ALREADY_DE_ACTIVE: "Proprietà già disattivata",
        ALREADY_ADDED: "Città già aggiunta",
        INVALID_CART: "Carrello vuoto. Si prega di aggiungere spazio",
        USER_NOT_FOUND: "Nessun utente trovato. Non è possibile procedere con la prenotazione",
        BOOKING_NOT_FOUND: "Prenotazione non trovata",
        BOOKING_ACCEPTED: "Prenotazione accettata",
        BOOKING_REJECT: "Prenotazione rifiutata",
        WISHLIST_USER: "Accedi come utente per usufruire di questa funzionalità",
        NO_UNITS_AVAILABLE: "Spiacenti! Non ci sono unità disponibili",
        NO_SPACE_AVAILABLE: "Non è disponibile nessuna unità per il periodo di tempo selezionato.",
        COHOST_DELETED: "Co-host eliminato correttamente",
        INVALID_REDEMPTION_CODE: "La carta regalo che hai inserito non è valida.",
        ALREADY_REDEEMED: "La carta regalo è già stata utilizzata.",
        DUPLICATE_HOLIDAY_DATE: "La data esiste già, selezionare un'altra data",
        OFFLINE_BOOKING_FOUND: "Nessuna prenotazione online trovata!",
        NO_SLOTS_AVAILABLE: 'Sfortunatamente, lo slot selezionato non è disponibile!',
        NO_PRICE_AVAILABLE: 'Prezzo non disponibile!',
        //new
        BAD_EMPLOYEE_REQUEST: `Hey! You cannot perform this action since these units are already distributed between partners and to continue to perform this action, please update the units assigned to your partners first.`,
        PROPERTY_NOT_ACTIVE : 'Property is not active!'
    },
    pl: {
        PRICE_TOO_LOW: 'Price must be larger than or equal to 1',
        INCOMPLETE_PROFILE: `Your profile/company details are incomplete.Please complete !`,
        INCOMPLETE_FLOOR_DETAILS: "You are not allowed to publish property with incomplete floor details!",
        NOT_FOUND: "Nie znaleziono obiektu",
        NOT_AUTHRIZED: "Nie masz uprawnień do aktualizowania tego obiektu",
        NOT_VERIFIED: "Twoje konto nie zostało jeszcze zweryfikowane przez administratora.",
        NOT_ALLOWED: "Nie masz uprawnień do dodania tego obiektu",
        PROPERTY_UPDATED: "Obiekt został pomyślnie zaktualizowany",
        PROPERTY_SAVED: "Obiekt został pomyślnie zapisany",
        PROPERTY_DELETED_SUCCESSFULLY: "Obiekt został pomyślnie usunięty",
        SPACE_DELETED_SUCCESSFULLY: "Obiekt został pomyślnie usunięty",
        PROPERTY_ACTIVATED: "Obiekt został aktywowany",
        PROPERTY_ALREADY_ACTIVE: "Obiekt jest już aktywny",
        PROPERTY_DE_ACTIVATED: "Obiekt został wyłączony",
        COHOST_DE_ACTIVATED: "Konto współgospodarza zostało pomyślnie wyłączone ",
        COHOST_ACTIVATED: "Konto współgospodarza zostało pomyślnie aktywowane",
        PROPERTY_ALREADY_DE_ACTIVE: "Obiekt został już wyłączony",
        ALREADY_ADDED: "Miejscowość została już dodana",
        INVALID_CART: "Pusty kosz, dodaj miejsce",
        USER_NOT_FOUND: "Nie znaleziono użytkownika, nie można kontynuować rezerwacji",
        BOOKING_NOT_FOUND: "Nie znaleziono rezerwacji",
        BOOKING_ACCEPTED: "Zaakceptowano rezerwację",
        BOOKING_REJECT: "Odrzucono rezerwację",
        WISHLIST_USER: "Zaloguj się jako użytkownik, aby móc korzystać z tej funkcjonalności",
        NO_UNITS_AVAILABLE: "Niestety! Nie ma więcej jednostek",
        NO_SPACE_AVAILABLE: "Brak dostępnych miejsc w wybranym okresie.",
        COHOST_DELETED: "Współgospodarz został pomyślnie usunięty",
        INVALID_REDEMPTION_CODE: "Podana karta podarunkowa jest nieprawidłowa.",
        ALREADY_REDEEMED: "Karta podarunkowa została już wykorzystana.",
        DUPLICATE_HOLIDAY_DATE: "Data już istnieje, wybierz inną datę",
        OFFLINE_BOOKING_FOUND: "Nie znaleziono rezerwacji online!",
        NO_SLOTS_AVAILABLE: 'Wybrany slot nie jest niestety dostępny!',
        NO_PRICE_AVAILABLE: 'Brak ceny!',
        //new
        BAD_EMPLOYEE_REQUEST: `Hey! You cannot perform this action since these units are already distributed between partners and to continue to perform this action, please update the units assigned to your partners first.`,
        PROPERTY_NOT_ACTIVE : 'Property is not active!'
    },
    ro: {
        PRICE_TOO_LOW: 'Price must be larger than or equal to 1',
        INCOMPLETE_PROFILE: `Your profile/company details are incomplete.Please complete !`,
        INCOMPLETE_FLOOR_DETAILS: "You are not allowed to publish property with incomplete floor details!",
        NOT_FOUND: "Proprietatea nu a fost găsită",
        NOT_AUTHRIZED: "Nu sunteți autorizat să actualizați această proprietate",
        NOT_VERIFIED: "Contul dvs. nu a fost încă verificat de către administrator.",
        NOT_ALLOWED: "Nu sunteți autorizat să adăugați această proprietate",
        PROPERTY_UPDATED: "Proprietate actualizată cu succes",
        PROPERTY_SAVED: "Proprietate salvată cu succes",
        PROPERTY_DELETED_SUCCESSFULLY: "Proprietate ștersă cu succes",
        SPACE_DELETED_SUCCESSFULLY: "Proprietate ștersă cu succes",
        PROPERTY_ACTIVATED: "Proprietate activată",
        PROPERTY_ALREADY_ACTIVE: "Proprietate deja activă",
        PROPERTY_DE_ACTIVATED: "Proprietate dezactivată",
        COHOST_DE_ACTIVATED: "Cont Co-gazdă dezactivat cu succes",
        COHOST_ACTIVATED: "Cont Co-gazdă activat cu succes",
        PROPERTY_ALREADY_DE_ACTIVE: "Proprietate deja dezactivată",
        ALREADY_ADDED: "Oraș deja adăugat",
        INVALID_CART: "Coș gol, vă rugăm să adăugați un spațiu",
        USER_NOT_FOUND: "Nu s-a găsit niciun utilizator, nu se poate continua rezervarea",
        BOOKING_NOT_FOUND: "Rezervarea nu a fost găsită",
        BOOKING_ACCEPTED: "Rezervare acceptată",
        BOOKING_REJECT: "Rezervare respinsă",
        WISHLIST_USER: "Vă rugăm să vă autentificați ca utilizator pentru a beneficia de această funcționalitate",
        NO_UNITS_AVAILABLE: "Din păcate! Nu au mai rămas alte spații",
        NO_SPACE_AVAILABLE: "Nu există alte spații disponibile pentru perioada de timp selectată.",
        COHOST_DELETED: "Cont Co-gazdă șters cu succes",
        INVALID_REDEMPTION_CODE: "Cardul cadou pe care l-ați introdus nu este valabil.",
        ALREADY_REDEEMED: "Cardul cadou a fost deja utilizat.",
        DUPLICATE_HOLIDAY_DATE: "Data există deja, selectați o altă dată",
        OFFLINE_BOOKING_FOUND: "Nu a fost găsită nicio rezervare online!",
        NO_SLOTS_AVAILABLE: 'Din păcate, slotul selectat nu este disponibil!',
        NO_PRICE_AVAILABLE: 'Prețul nu este disponibil!',
        //new
        BAD_EMPLOYEE_REQUEST: `Hey! You cannot perform this action since these units are already distributed between partners and to continue to perform this action, please update the units assigned to your partners first.`,
        PROPERTY_NOT_ACTIVE : 'Property is not active!'
    },
    ru: {
        PRICE_TOO_LOW: 'Price must be larger than or equal to 1',
        INCOMPLETE_PROFILE: `Your profile/company details are incomplete.Please complete !`,
        INCOMPLETE_FLOOR_DETAILS: "You are not allowed to publish property with incomplete floor details!",
        NOT_FOUND: "Объект недвижимости не найден",
        NOT_AUTHRIZED: "У вас нет прав для обновления этого объекта недвижимости",
        NOT_VERIFIED: "Ваша учетная запись еще не проверена администратором.",
        NOT_ALLOWED: "У вас нет прав на добавление этого объекта недвижимости",
        PROPERTY_UPDATED: "Объект недвижимости обновлен",
        PROPERTY_SAVED: "Объект недвижимости сохранен",
        PROPERTY_DELETED_SUCCESSFULLY: "Объект недвижимости удален",
        SPACE_DELETED_SUCCESSFULLY: "Объект недвижимости удален",
        PROPERTY_ACTIVATED: "Объект недвижимости активен",
        PROPERTY_ALREADY_ACTIVE: "Объект недвижимости уже активен",
        PROPERTY_DE_ACTIVATED: "Объект недвижимости неактивен",
        COHOST_DE_ACTIVATED: "Учетная запись совладельца деактивирована",
        COHOST_ACTIVATED: "Аккаунт совладельца активирован",
        PROPERTY_ALREADY_DE_ACTIVE: "Объект недвижимости уже неактивен",
        ALREADY_ADDED: "Город уже добавлен",
        INVALID_CART: "Пустая корзина: добавьте помещение",
        USER_NOT_FOUND: "Пользователь не найден: бронирование невозможно",
        BOOKING_NOT_FOUND: "Бронирование не найдено",
        BOOKING_ACCEPTED: "Бронирование принято",
        BOOKING_REJECT: "Бронирование отклонено",
        WISHLIST_USER: "Чтобы воспользоваться этой функцией, войдите в систему в качестве пользователя",
        NO_UNITS_AVAILABLE: "Сожалеем! Все помещения заняты",
        NO_SPACE_AVAILABLE: "Не осталось свободных помещений на выбранный период.",
        COHOST_DELETED: "Совладелец удален",
        INVALID_REDEMPTION_CODE: "Введенный номер подарочной карты недействителен.",
        ALREADY_REDEEMED: "Подарочная карта уже использована.",
        DUPLICATE_HOLIDAY_DATE: "Эта дата уже существует: выберите другую",
        OFFLINE_BOOKING_FOUND: "Онлайн-бронирование не найдено!",
        NO_SLOTS_AVAILABLE: 'К сожалению, выбранный промежуток недоступен!',
        NO_PRICE_AVAILABLE: 'Цена недоступна!',
        //new
        BAD_EMPLOYEE_REQUEST: `Hey! You cannot perform this action since these units are already distributed between partners and to continue to perform this action, please update the units assigned to your partners first.`,
        PROPERTY_NOT_ACTIVE : 'Property is not active!'
    },
    es: {
        PRICE_TOO_LOW: 'Price must be larger than or equal to 1',
        INCOMPLETE_PROFILE: `Your profile/company details are incomplete.Please complete !`,
        INCOMPLETE_FLOOR_DETAILS: "You are not allowed to publish property with incomplete floor details!",
        NOT_FOUND: "Propiedad no encontrada",
        NOT_AUTHRIZED: "No estás autorizado para actualizar esta propiedad",
        NOT_VERIFIED: "Tu cuenta aún no ha sido verificada por el administrador.",
        NOT_ALLOWED: "No estás autorizado para añadir esta propiedad",
        PROPERTY_UPDATED: "La propiedad se ha actualizado correctamente",
        PROPERTY_SAVED: "La propiedad se ha guardado correctamente",
        PROPERTY_DELETED_SUCCESSFULLY: "La propiedad se ha eliminado correctamente",
        SPACE_DELETED_SUCCESSFULLY: "La propiedad se ha eliminado correctamente",
        PROPERTY_ACTIVATED: "Propiedad activada",
        PROPERTY_ALREADY_ACTIVE: "La propiedad ya está activa",
        PROPERTY_DE_ACTIVATED: "Propiedad desactivada",
        COHOST_DE_ACTIVATED: "La cuenta de coanfitrión se ha desactivado correctamente",
        COHOST_ACTIVATED: "La cuenta de coanfitrión se ha activado correctamente",
        PROPERTY_ALREADY_DE_ACTIVE: "La propiedad ya está desactivada",
        ALREADY_ADDED: "La localidad ya se ha añadido",
        INVALID_CART: "Carro vacío; añada un espacio",
        USER_NOT_FOUND: "No se ha encontrado ningún usuario; no es posible continuar con la reserva",
        BOOKING_NOT_FOUND: "No se ha encontrado la reserva",
        BOOKING_ACCEPTED: "Reserva aceptada",
        BOOKING_REJECT: "Reserva rechazada",
        WISHLIST_USER: "Inicia sesión como usuario para aprovechar esta función",
        NO_UNITS_AVAILABLE: "Lamentablemente no quedan más unidades",
        NO_SPACE_AVAILABLE: "No hay más unidades de espacio disponibles para el período de tiempo seleccionado.",
        COHOST_DELETED: "El coanfitrión se ha eliminado correctamente",
        INVALID_REDEMPTION_CODE: "La tarjeta regalo que has introducido no es válida.",
        ALREADY_REDEEMED: "La tarjeta regalo ya ha sido canjeada.",
        DUPLICATE_HOLIDAY_DATE: "La fecha ya existe, selecciona otra fecha",
        OFFLINE_BOOKING_FOUND: "¡No se ha encontrado ninguna reserva online!",
        NO_SLOTS_AVAILABLE: '¡Desafortunadamente, la ranura seleccionada no está disponible!',
        NO_PRICE_AVAILABLE: '¡Precio no disponible!',
        //new
        BAD_EMPLOYEE_REQUEST: `Hey! You cannot perform this action since these units are already distributed between partners and to continue to perform this action, please update the units assigned to your partners first.`,
        PROPERTY_NOT_ACTIVE : 'Property is not active!'
    },
    tr: {
        PRICE_TOO_LOW: 'Price must be larger than or equal to 1',
        INCOMPLETE_PROFILE: `Your profile/company details are incomplete.Please complete !`,
        INCOMPLETE_FLOOR_DETAILS: "You are not allowed to publish property with incomplete floor details!",
        NOT_FOUND: "Emlak bulunamadı",
        NOT_AUTHRIZED: "Bu emlakı güncelleme yetkiniz yok",
        NOT_VERIFIED: "Hesabınız henüz yönetici tarafından doğrulanmadı.",
        NOT_ALLOWED: "Bu emlakı ekleme yetkiniz yok",
        PROPERTY_UPDATED: "Emlak güncellenmiştir",
        PROPERTY_SAVED: "Emlak kaydedilmiştir",
        PROPERTY_DELETED_SUCCESSFULLY: "Emlak silinmiştir",
        SPACE_DELETED_SUCCESSFULLY: "Emlak silinmiştir",
        PROPERTY_ACTIVATED: "Emlak etkinleştirildi",
        PROPERTY_ALREADY_ACTIVE: "Emlak zaten etkin",
        PROPERTY_DE_ACTIVATED: "Emlak devre dışı bırakıldı",
        COHOST_DE_ACTIVATED: "Eş sunucu hesabı devre dışı bırakılmıştır",
        COHOST_ACTIVATED: "Eş sunucu hesabı etkinleştirilmiştir",
        PROPERTY_ALREADY_DE_ACTIVE: "Emlak zaten devre dışı",
        ALREADY_ADDED: "Şehir zaten eklenmiş",
        INVALID_CART: "Sepet boş, lütfen mekân ekleyin",
        USER_NOT_FOUND: "Kullanıcı bulunamadı, rezervasyona devam edilemez",
        BOOKING_NOT_FOUND: "Rezervasyon bulunamadı",
        BOOKING_ACCEPTED: "Rezervasyon Kabul Edildi",
        BOOKING_REJECT: "Rezervasyon Reddedildi",
        WISHLIST_USER: "Bu işlevsellikten yararlanmak için lütfen kullanıcı olarak oturum açın",
        NO_UNITS_AVAILABLE: "Maalesef! Hiç birim kalmadı",
        NO_SPACE_AVAILABLE: "Seçilen zaman aralığında boş mekân birimi kalmadı.",
        COHOST_DELETED: "Eş sunucu  silinmiştir",
        INVALID_REDEMPTION_CODE: "Girdiğiniz hediye kartı geçerli değil.",
        ALREADY_REDEEMED: "Hediye kartı önceden kullanılmış.",
        DUPLICATE_HOLIDAY_DATE: "Tarih zaten girilmiş, lütfen başka tarih seçin",
        OFFLINE_BOOKING_FOUND: "Çevrimiçi rezervasyon bulunamadı!",
        NO_SLOTS_AVAILABLE: 'Maalesef, seçilen bölme mevcut değil!',
        NO_PRICE_AVAILABLE: 'Fiyat mevcut değil!',
        //new
        BAD_EMPLOYEE_REQUEST: `Hey! You cannot perform this action since these units are already distributed between partners and to continue to perform this action, please update the units assigned to your partners first.`,
        PROPERTY_NOT_ACTIVE : 'Property is not active!'
    },
};

export default (lang: string) => ({
    INCOMPLETE_FLOOR_DETAILS: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].INCOMPLETE_FLOOR_DETAILS },
    ALREADY_ADDED: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].ALREADY_ADDED },
    NO_UNITS_AVAILABLE: { httpCode: HTTP.NOT_FOUND, statusCode: 400, message: MSG[lang].NO_UNITS_AVAILABLE },
    NO_SPACE_AVAILABLE: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].NO_SPACE_AVAILABLE },
    NOT_FOUND: { httpCode: HTTP.NOT_FOUND, statusCode: 404, message: MSG[lang].NOT_FOUND },
    WISHLIST_USER: { httpCode: HTTP.NOT_FOUND, statusCode: 400, message: MSG[lang].WISHLIST_USER },
    USER_NOT_FOUND: { httpCode: HTTP.NOT_FOUND, statusCode: 404, message: MSG[lang].USER_NOT_FOUND },
    INVALID_CART: { httpCode: HTTP.NOT_FOUND, statusCode: 404, message: MSG[lang].INVALID_CART },
    PRICE_TOO_LOW: { httpCode: HTTP.NOT_FOUND, statusCode: 404, message: MSG[lang].PRICE_TOO_LOW },
    INVALID_REDEMPTION_CODE: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].INVALID_REDEMPTION_CODE },
    ALREADY_REDEEMED: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].ALREADY_REDEEMED },
    INVALID_BOOKING_ID: { httpCode: HTTP.NOT_FOUND, statusCode: 404, message: MSG[lang].INVALID_BOOKING_ID },
    NOT_AUTHRIZED: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].NOT_AUTHRIZED },
    NOT_ALLOWED: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].NOT_ALLOWED },
    INCOMPLETE_PROFILE: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].INCOMPLETE_PROFILE },
    NOT_VERIFIED: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].NOT_VERIFIED },
    PROPERTY_UPDATED: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].PROPERTY_UPDATED },
    BAD_EMPLOYEE_REQUEST: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].BAD_EMPLOYEE_REQUEST },
    PROPERTY_SAVED: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].PROPERTY_SAVED },
    PROPERTY_CLAIMED_RQUEST: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].PROPERTY_CLAIMED_RQUEST },
    PROPERTY_DELETED_SUCCESSFULLY: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].PROPERTY_DELETED_SUCCESSFULLY },
    SPACE_DELETED_SUCCESSFULLY: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].SPACE_DELETED_SUCCESSFULLY },
    PROPERTY_ACTIVATED: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].PROPERTY_ACTIVATED },
    PROPERTY_ALREADY_ACTIVE: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].PROPERTY_ALREADY_ACTIVE },
    PROPERTY_DE_ACTIVATED: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].PROPERTY_DE_ACTIVATED },
    COHOST_DE_ACTIVATED: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].COHOST_DE_ACTIVATED },
    COHOST_ACTIVATED: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].COHOST_ACTIVATED },
    COHOST_DELETED: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].COHOST_DELETED },
    PROPERTY_ALREADY_DE_ACTIVE: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].PROPERTY_ALREADY_DE_ACTIVE },
    BOOKING_NOT_FOUND: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].BOOKING_NOT_FOUND },
    OFFLINE_BOOKING_FOUND: { httpCode: HTTP.BAD_REQUEST, statusCode: 411, message: MSG[lang].OFFLINE_BOOKING_FOUND },
    BOOKING_ACCEPTED: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].BOOKING_ACCEPTED },
    BOOKING_REJECT: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].BOOKING_REJECT },
    DUPLICATE_HOLIDAY_DATE: { httpCode: HTTP.SUCCESS, statusCode: 400, message: MSG[lang].DUPLICATE_HOLIDAY_DATE },
    /* newLang */ NO_SLOTS_AVAILABLE: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].NO_SLOTS_AVAILABLE },
    /* newLang */ NO_PRICE_AVAILABLE: { httpCode: HTTP.BAD_REQUEST, statusCode: 411, message: MSG[lang].NO_PRICE_AVAILABLE },
    PROPERTY_CLAMIED_ERROR: { httpCode: HTTP.SUCCESS, statusCode: 400, message: MSG[lang].PROPERTY_CLAMIED_ERROR },
    PROPERTY_NOT_ACTIVE :  { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].PROPERTY_NOT_ACTIVE }

});