/**
 * @file user.response
 * @description defines response for user entity
 * @created 2019-08-29 00:39:36
 * @author Desk Now Dev Team
 * @meta Response Code: 50XX, 51XX
*/

import HTTP from "./code.response";

export const MSG: any = {
    en: {
        NOT_ALLOWED: `There is no phone number associated with this account. Please try other login methods.`,
        NOT_FOUND: 'User not found',
        EMAIL_ALREADY_EXISTS: "This email already exist",
        PHONE_ALREADY_EXISTS: "This phone number already exists",
        SIGNUP_SUCCESSFULLY: "Signup successfully, One time passcode sent to your mobile number",
        OTP_SENT_SUCCESSFULLY: "OTP sent successfully",
        OTP_INVALID: "Invalid OTP",
        OTP_LIMIT_EXHAUSTED: `OTP limit exhausted.Please try again after 5 minutes`,
        OTP_VERIFIED: "OTP verified successfully",
        OTP_EXPIRED: "OTP expired",
        INCORRECT_PASSWORD: 'Password is incorrect',
        LOGIN_SUCCESSFULLY: 'User Login SUCCESSFULLY',
        ALREADY_BLOCKED: "User is blocked",
        USER_BLOCKED_SUCCESSFULLY: "User is blocked successfully",
        USER_ALREADY_ACTIVE: "User is already active",
        USER_ALREADY_EXISTS: "User is already active",
        COHOST_ALREADY_EXIST: "You have already invited this user as co-host.",
        COHOST_ALREADY_ASSOCIATED: "User with these details already associated with another account",
        USER_UNBLOCKED_SUCCESSFULLY: "User unblocked successfully",
        USER_ALREADY_DELETED: "User already deleted",
        USER_DELETED_SUCCESSFULLY: "User deleted successfully",
        Email_NOT_VERIFIED: 'User Email Is Not Verified',
        PAYOUT_ALREADY_CREATED: 'Already created',
        Email_VERIFIED: 'User Email Is Verified Successfully',
        MAIL_VERIFICATIO_LINK: 'Mail verification link sent successfully',
        LINK_EXPIRED: 'Verification Link Has Expired ',
        LINKEDIN_ERROR: `Authorization error! please retry.`,
        PASSWORD_CHANGED_SUCCESSFULLY: 'Your password has been changed successfully.Kindly login to continue.',
        ACCOUNT_BLOCKED: 'Your account has been temporarily blocked.',
        TOKEN_EXPIRED: 'Token Expired',
        LOGGED_OUT_SUCCESSFULLY: 'You have been logged out from DeskNow',
        USER_FOUND_SUCCESSFULLY: 'User Information',
        INVALID_RESET_TOKEN: 'Invalid reset token',
        VALID_RESET_TOKEN: 'Valid reset token',
        AMINTIES_LISTING: 'List of amenities.',
        PARENT_CATEGORIES: 'List of parent categories',
        CHILD_CATEGORIES: 'List of child categories',
        NOT_EXISTS: " Not Exists",
        PHONE_NOT_VERIFIED: "Phone not verified.",
        HOST_EXISTS: "Host exists.",
        USER_EXISTS: "User exists.",
        EXISTS: "Phone Number Exists.",
        EMAIL_ALREADY_EXISTS_AS_HOST: "This email is already registered as host",
        EMAIL_ALREADY_EXISTS_AS_USER: "This email is already registered as user",
        USER_EXISTS_AS_COMPANY: "User Exists as company",
        INVALID_EMAIL: 'Invalid Email',
        COWORKER_EXISTS: 'COWORKER ALREADY INVITED',
        USER_ELIGIBLE: 'User eligible for coworker',
        USER_NOT_FOUND: 'User Not found',
        CHECK_SELF: 'You cannot add yourself',
        CHECK_AVAILABILITY: `You can't add more coworkers.Capacity is full`,
        ACCOUNT_DELETED: 'Your Account Has Been Deleted successfully',
        INCORRECT_OLD_PASSWORD: 'Your old password is incorrect',
        AMOUNT_TOO_SMALL: 'Amount too small',
        GIFTCARD_NOT_FOUND: 'Invalid Giftcard Number',
        GIFTCARD_APPLIED: 'Giftcard Applied SUccessfully',
        EMPLOYEE_EMAIL_ALREADY_EXISTS: 'Employee with this email is already added',
        EMPLOYEE_PHONE_ALREADY_EXISTS: 'Employee with this phone number is already added'
    },
    cs: {
        EMPLOYEE_EMAIL_ALREADY_EXISTS: 'Employee with this email is already added',
        EMPLOYEE_PHONE_ALREADY_EXISTS: 'Employee with this phone number is already added',
        NOT_ALLOWED: "S tímto účtem není spojeno žádné telefonní číslo. Vyzkoušejte jiné způsoby přihlášení.",
        NOT_FOUND: "Uživatel nenalezen",
        EMAIL_ALREADY_EXISTS: "Tento e-mail již existuje",
        PHONE_ALREADY_EXISTS: "Toto telefonní číslo již existuje",
        SIGNUP_SUCCESSFULLY: "Registrace proběhla úspěšně, jednorázový přístupový kód byl odeslán na vaše telefonní číslo",
        OTP_SENT_SUCCESSFULLY: "OTP kód byl úspěšně odeslán",
        OTP_INVALID: "Neplatný OTP kód",
        OTP_LIMIT_EXHAUSTED: "Dosaženo limitu OTP kódu. Zkuste to znovu po 5 minutách",
        OTP_VERIFIED: "OTP kód byl úspěšně ověřen",
        OTP_EXPIRED: "Platnost OTP kódu vypršela",
        INCORRECT_PASSWORD: " Nesprávné heslo",
        LOGIN_SUCCESSFULLY: "Přihlášení bylo ÚSPĚŠNÉ",
        ALREADY_BLOCKED: "Uživatel je zablokován",
        USER_BLOCKED_SUCCESSFULLY: "Uživatel je úspěšně zablokován",
        USER_ALREADY_ACTIVE: "Uživatel je již aktivní",
        USER_ALREADY_EXISTS: "Uživatel je již aktivní",
        COHOST_ALREADY_EXIST: "Již jste pozvali tohoto uživatele jako spoluhostitele.",
        COHOST_ALREADY_ASSOCIATED: "Uživatel s těmito údaji je již přiřazen k jinému účtu",
        USER_UNBLOCKED_SUCCESSFULLY: "Uživatel byl úspěšně odblokován",
        USER_ALREADY_DELETED: "Uživatel by již smazán",
        USER_DELETED_SUCCESSFULLY: "Uživatel byl úspěšně smazán",
        Email_NOT_VERIFIED: "E-mail uživatele není ověřen",
        PAYOUT_ALREADY_CREATED: "Již vytvořeno",
        Email_VERIFIED: "E-mail uživatele je úspěšně ověřen",
        MAIL_VERIFICATIO_LINK: "Odkaz pro ověření e-mailu byl úspěšně odeslán",
        LINK_EXPIRED: "Platnost odkazu na ověření vypršela ",
        LINKEDIN_ERROR: "Chyba autorizace! zkuste to znovu.",
        PASSWORD_CHANGED_SUCCESSFULLY: "Vaše heslo bylo úspěšně změněno. Pro pokračování se přihlaste.",
        ACCOUNT_BLOCKED: "Váš účet byl dočasně zablokován.",
        TOKEN_EXPIRED: "Platnost tokenu vypršela",
        LOGGED_OUT_SUCCESSFULLY: "Byli jste odhlášeni z DeskNow",
        USER_FOUND_SUCCESSFULLY: "Informace pro uživatele",
        INVALID_RESET_TOKEN: "Neplatný resetovací token",
        VALID_RESET_TOKEN: "Platný resetovací token",
        AMINTIES_LISTING: "Seznam vybavení.",
        PARENT_CATEGORIES: "Seznam nadřazených kategorií",
        CHILD_CATEGORIES: "Seznam podřízených kategorií",
        NOT_EXISTS: " Neexistuje",
        PHONE_NOT_VERIFIED: "Telefon nebyl ověřen.",
        HOST_EXISTS: "Hostitel existuje.",
        USER_EXISTS: "Uživatel existuje.",
        EXISTS: "Telefonní číslo existuje.",
        EMAIL_ALREADY_EXISTS_AS_HOST: "Tento e-mail je již zaregistrován jako hostitel",
        EMAIL_ALREADY_EXISTS_AS_USER: "Tento e-mail je již zaregistrován jako uživatel",
        USER_EXISTS_AS_COMPANY: "Uživatel existuje jako společnost",
        INVALID_EMAIL: "Neplatný e-mail",
        COWORKER_EXISTS: "SPOLUPRACOVNÍK BYL JIŽ POZVÁN",
        USER_ELIGIBLE: "Vhodný uživatel pro spolupracovníka",
        USER_NOT_FOUND: "Uživatel nebyl nalezen",
        CHECK_SELF: "Nemůžete přidat sebe",
        CHECK_AVAILABILITY: "Nemůžete přidat další spolupracovníky. Dosaženo maximální kapacity",
        ACCOUNT_DELETED: "Váš účet byl úspěšně smazán",
        INCORRECT_OLD_PASSWORD: "Staré heslo je nesprávné",
        AMOUNT_TOO_SMALL: "Částka je příliš malá",
        GIFTCARD_NOT_FOUND: "Neplatné číslo dárkové karty",
        GIFTCARD_APPLIED: "Dárková karta byla úspěšně použita"
    },
    nl: {
        EMPLOYEE_EMAIL_ALREADY_EXISTS: 'Employee with this email is already added',
        EMPLOYEE_PHONE_ALREADY_EXISTS: 'Employee with this phone number is already added',
        NOT_ALLOWED: "Er is geen telefoonnummer gekoppeld aan dit account. Probeer andere inlogmethoden.",
        NOT_FOUND: "Gebruiker niet gevonden",
        EMAIL_ALREADY_EXISTS: "Het opgegeven e-mailadres bestaat al",
        PHONE_ALREADY_EXISTS: "Dit telefoonnummer bestaat al",
        SIGNUP_SUCCESSFULLY: "Succesvol aangemeld, er is een eenmalige toegangscode verzonden naar uw mobiele nummer",
        OTP_SENT_SUCCESSFULLY: "OTP is succesvol verzonden",
        OTP_INVALID: "Ongeldige OTP",
        OTP_LIMIT_EXHAUSTED: "OTP-limiet is verstreken. Probeer het na 5 minuten opnieuw",
        OTP_VERIFIED: "OTP succesvol bevestigd.",
        OTP_EXPIRED: "OTP is verlopen",
        INCORRECT_PASSWORD: "Wachtwoord is onjuist",
        LOGIN_SUCCESSFULLY: "SUCCESVOLLE aanmelding door gebruiker",
        ALREADY_BLOCKED: "Gebruiker is geblokkeerd",
        USER_BLOCKED_SUCCESSFULLY: "Gebruiker is succesvol geblokkeerd",
        USER_ALREADY_ACTIVE: "Gebruiker is al actief",
        USER_ALREADY_EXISTS: "Gebruiker is al actief",
        COHOST_ALREADY_EXIST: "U heeft deze gebruiker al uitgenodigd als cohost.",
        COHOST_ALREADY_ASSOCIATED: "Gebruiker met deze gegevens is al gekoppeld aan een ander account",
        USER_UNBLOCKED_SUCCESSFULLY: "Gebruiker succesvol gedeblokkeerd",
        USER_ALREADY_DELETED: "Gebruiker is al verwijderd",
        USER_DELETED_SUCCESSFULLY: "Verwijderen van gebruiker is succesvol.",
        Email_NOT_VERIFIED: "E-mailadres van gebruiker is niet geverifieerd",
        PAYOUT_ALREADY_CREATED: "Al aangemaakt",
        Email_VERIFIED: "Het e-mailadres van de gebruiker is succesvol geverifieerd",
        MAIL_VERIFICATIO_LINK: "E-mailverificatielink is succesvol verzonden",
        LINK_EXPIRED: "Verificatielink is verlopen ",
        LINKEDIN_ERROR: "Autorisatiefout! probeer het opnieuw.",
        PASSWORD_CHANGED_SUCCESSFULLY: "Uw wachtwoord is succesvol gewijzigd. Log in om verder te gaan.",
        ACCOUNT_BLOCKED: "Uw account is tijdelijk geblokkeerd.",
        TOKEN_EXPIRED: "Token is verlopen",
        LOGGED_OUT_SUCCESSFULLY: "U bent uitgelogd bij DeskNow",
        USER_FOUND_SUCCESSFULLY: "Gebruikersinfo",
        INVALID_RESET_TOKEN: "Ongeldig reset-token",
        VALID_RESET_TOKEN: "Geldig reset-token",
        AMINTIES_LISTING: "Lijst met voorzieningen.",
        PARENT_CATEGORIES: "Lijst met bovenliggende categorieën",
        CHILD_CATEGORIES: "Lijst met onderliggende categorieën",
        NOT_EXISTS: "Bestaat niet",
        PHONE_NOT_VERIFIED: "Telefoonnr. niet geverifieerd",
        HOST_EXISTS: "Host bestaat.",
        USER_EXISTS: "Gebruiker bestaat.",
        EXISTS: "Telefoonnummer bestaat.",
        EMAIL_ALREADY_EXISTS_AS_HOST: "Dit e-mailadres is al geregistreerd als host.",
        EMAIL_ALREADY_EXISTS_AS_USER: "Dit e-mailadres is al geregistreerd als gebruiker.",
        USER_EXISTS_AS_COMPANY: "Gebruiker bestaat als bedrijf",
        INVALID_EMAIL: "Ongeldig e-mailadres",
        COWORKER_EXISTS: "COWORKER AL UITGENODIGD",
        USER_ELIGIBLE: "Gebruiker komt in aanmerking voor coworker",
        USER_NOT_FOUND: "Gebruiker niet gevonden",
        CHECK_SELF: "Kan eigen account niet toevoegen",
        CHECK_AVAILABILITY: "U kunt geen coworker meer toevoegen. De capaciteit is vol",
        ACCOUNT_DELETED: "Uw account is met succes verwijderd",
        INCORRECT_OLD_PASSWORD: "Uw oude wachtwoord is onjuist",
        AMOUNT_TOO_SMALL: "Bedrag te klein",
        GIFTCARD_NOT_FOUND: "Ongeldig cadeaubonnummer",
        GIFTCARD_APPLIED: "Cadeaubon succesvol toegepast"
    },
    fr: {
        EMPLOYEE_EMAIL_ALREADY_EXISTS: 'Employee with this email is already added',
        EMPLOYEE_PHONE_ALREADY_EXISTS: 'Employee with this phone number is already added',
        NOT_ALLOWED: "Aucun numéro de téléphone n'est associé à ce compte. Veuillez essayer d'autres méthodes de connexion.",
        NOT_FOUND: "Utilisateur introuvable",
        EMAIL_ALREADY_EXISTS: "Cet adresse e-mail existe déjà",
        PHONE_ALREADY_EXISTS: "Ce numéro de téléphone existe déjà",
        SIGNUP_SUCCESSFULLY: "Inscription réussie, un code à usage unique a été envoyé à votre numéro de mobile",
        OTP_SENT_SUCCESSFULLY: "Le code à usage unique à été envoyé avec succès",
        OTP_INVALID: "Code à usage unique invalide",
        OTP_LIMIT_EXHAUSTED: "Limite des codes à usage unique épuisée. Veuillez réessayer après 5 minutes",
        OTP_VERIFIED: "Le code à usage unique a été vérifié avec succès",
        OTP_EXPIRED: "Le code à usage unique à expiré",
        INCORRECT_PASSWORD: "Le mot de passe est incorrect",
        LOGIN_SUCCESSFULLY: "Connexion utilisateur RÉUSSIE",
        ALREADY_BLOCKED: "L'utilisateur est bloqué",
        USER_BLOCKED_SUCCESSFULLY: "L'utilisateur a été bloqué avec succès",
        USER_ALREADY_ACTIVE: "L'utilisateur est déjà actif",
        USER_ALREADY_EXISTS: "L'utilisateur est déjà actif",
        COHOST_ALREADY_EXIST: "Vous avez déjà invité cet utilisateur en tant que co-hôte.",
        COHOST_ALREADY_ASSOCIATED: "Un utilisateur avec ces détails est déjà associé à un autre compte",
        USER_UNBLOCKED_SUCCESSFULLY: "L'utilisateur a été débloqué avec succès",
        USER_ALREADY_DELETED: "L'utilisateur a déjà été supprimé",
        USER_DELETED_SUCCESSFULLY: "L'utilisateur a été supprimé avec succès",
        Email_NOT_VERIFIED: "L'adresse e-mail de l'utilisateur n'est pas vérifiée",
        PAYOUT_ALREADY_CREATED: "Déjà créé",
        Email_VERIFIED: "L'adresse e-mail de l'utilisateur a été vérifiée avec succès",
        MAIL_VERIFICATIO_LINK: "Le lien de vérification de l'adresse e-mail a été envoyé avec succès",
        LINK_EXPIRED: "Le lien de vérification a expiré ",
        LINKEDIN_ERROR: "Erreur d'autorisation ! veuillez réessayer.",
        PASSWORD_CHANGED_SUCCESSFULLY: "Votre mot de passe a été modifié avec succès. Veuillez vous connecter pour continuer.",
        ACCOUNT_BLOCKED: "Votre compte a été temporairement bloqué.",
        TOKEN_EXPIRED: "Jeton expiré",
        LOGGED_OUT_SUCCESSFULLY: "Vous avez été déconnecté(e) de DeskNow",
        USER_FOUND_SUCCESSFULLY: "Informations de l’utilisateur",
        INVALID_RESET_TOKEN: "Jeton de réinitialisation non valide",
        VALID_RESET_TOKEN: "Jeton de réinitialisation valide",
        AMINTIES_LISTING: "Liste des équipements.",
        PARENT_CATEGORIES: "Liste des catégories parentes",
        CHILD_CATEGORIES: "Liste des catégories enfants",
        NOT_EXISTS: "N'existe pas",
        PHONE_NOT_VERIFIED: "Téléphone non vérifié.",
        HOST_EXISTS: "L'hôte existe.",
        USER_EXISTS: "L'utilisateur existe.",
        EXISTS: "Le numéro de téléphone existe.",
        EMAIL_ALREADY_EXISTS_AS_HOST: "Cette adresse e-mail est déjà enregistrée en tant qu'hôte",
        EMAIL_ALREADY_EXISTS_AS_USER: "Cette adresse e-mail est déjà enregistrée en tant qu'utilisateur",
        USER_EXISTS_AS_COMPANY: "L'utilisateur existe en tant qu'entreprise",
        INVALID_EMAIL: "Adresse e-mail invalide",
        COWORKER_EXISTS: "COLLABORATEUR DÉJÀ INVITÉ",
        USER_ELIGIBLE: "Utilisateur éligible en tant que collaborateur",
        USER_NOT_FOUND: "Utilisateur introuvable",
        CHECK_SELF: "Vous ne pouvez pas vous ajouter",
        CHECK_AVAILABILITY: "Vous ne pouvez pas ajouter d'autres collaborateurs. La capacité est atteinte",
        ACCOUNT_DELETED: "Votre compte a été supprimé avec succès",
        INCORRECT_OLD_PASSWORD: "Votre ancien mot de passe est incorrect",
        AMOUNT_TOO_SMALL: "Le montant est trop petit",
        GIFTCARD_NOT_FOUND: "Numéro de carte-cadeau invalide",
        GIFTCARD_APPLIED: "Carte cadeau appliquée avec succès"
    },
    de: {
        NOT_ALLOWED: `Die Telefonnummer stimmt nicht mit dem Konto überein. Bitte versuche eine andere Anmeldeoption`,
        NOT_FOUND: 'Nutzer nicht gefunden',
        EMAIL_ALREADY_EXISTS: "Die E-Mail Adresse exestiert bereits.",
        PHONE_ALREADY_EXISTS: "Die Telefonnummer exestiert bereits",
        SIGNUP_SUCCESSFULLY: "Anmeldung war erfolgreich! Ein einmaliger Verifizierungscode wurde an deine Telefonnummer gesendet",
        OTP_SENT_SUCCESSFULLY: "OTP erfolgreich versendet",
        OTP_INVALID: "Ungültiger OTP",
        OTP_LIMIT_EXHAUSTED: `OTP Limit wurde erreicht. Bitte versuche es in 5 Minuten erneut.`,
        OTP_VERIFIED: "OTP erfolgreich bestätigt",
        OTP_EXPIRED: "OTP abgelaufen",
        INCORRECT_PASSWORD: 'Das Passwort ist falsch',
        LOGIN_SUCCESSFULLY: 'Anmeldung war erfolgreich!',
        ALREADY_BLOCKED: "Nutzer wurde blockiert",
        USER_BLOCKED_SUCCESSFULLY: "Nutzer wurde erfolgreich blockiert",
        USER_ALREADY_ACTIVE: "Nutzer ist bereits aktiv",
        USER_ALREADY_EXISTS: "Nutzer exestiert bereits",
        COHOST_ALREADY_EXIST: "Dieser Benutzer wurde schon eingeladen.",
        COHOST_ALREADY_ASSOCIATED: "Es gibt bereits ein Konto mit diesen Angaben.",
        USER_UNBLOCKED_SUCCESSFULLY: "Nutzer wurde entblockt!",
        USER_ALREADY_DELETED: "Nutzer wurde bereits gelöscht.",
        USER_DELETED_SUCCESSFULLY: "Nutzer wurde erfolgreich gelöscht",
        Email_NOT_VERIFIED: 'Die E-Mail Adresse ist nicht verifiziert',
        PAYOUT_ALREADY_CREATED: 'Wurde bereits erstellt!',
        Email_VERIFIED: 'Nutzer E-Mail wurde erfolgreich bestätigt!',
        MAIL_VERIFICATIO_LINK: 'Verifizierungslink wurde an deine E-Mail verschickt!',
        LINK_EXPIRED: 'Diser Link ist abgelaufen',
        LINKEDIN_ERROR: `Berechtigung fehlerhaft! Versuceh es bitte erneut`,
        PASSWORD_CHANGED_SUCCESSFULLY: 'Dein Passwort wurde erfolgreich geändert. Bitte logge dich ein, um fortzufahren.',
        ACCOUNT_BLOCKED: 'Dein Konto wurde zeitweise gesperrt. Bitte wende dich an happy@desk-now.com',
        TOKEN_EXPIRED: 'Token ungültig',
        LOGGED_OUT_SUCCESSFULLY: 'Du wurdest erfolgreich ausgeloggt.',
        USER_FOUND_SUCCESSFULLY: 'Nutzerinformation',
        INVALID_RESET_TOKEN: 'Ungültiger reset Token',
        VALID_RESET_TOKEN: 'Gültiger reset Token',
        AMINTIES_LISTING: 'Liste der eigenschaften.',
        PARENT_CATEGORIES: 'Liste der Unterkategorien',
        CHILD_CATEGORIES: 'Liste der child Kategorien',
        NOT_EXISTS: "Exestiert nicht!",
        PHONE_NOT_VERIFIED: "Telefonnummer wurde nicht verifiziert!",
        HOST_EXISTS: "Host exists.",
        USER_EXISTS: "User exists.",
        EXISTS: "Telefonnummer existiert.",
        EMAIL_ALREADY_EXISTS_AS_HOST: "Diese E-Mail Adresse ist schon einem anderen Host Account zugeordnet",
        EMAIL_ALREADY_EXISTS_AS_USER: "Diese E-mail ist schon einem anderen Nutzer zugeordnet.",
        USER_EXISTS_AS_COMPANY: "Nutzer ist bereits als Unternehmen vorhanden",
        INVALID_EMAIL: 'Ungültige E-Mail',
        COWORKER_EXISTS: 'Kollege wurde bereits eingeladen',
        USER_ELIGIBLE: 'Nutzer ist berechtigt Kollegen einzuladen',
        USER_NOT_FOUND: 'Nutzer nicht gefunden',
        CHECK_SELF: 'Du kannst dich nicht selbst hinzufügen',
        CHECK_AVAILABILITY: `Du kannst keine weiteren Kollegen hinzufügen. Kapazität ist aufgebraucht.`,
        ACCOUNT_DELETED: 'Dein Account wurde erfolgreich gelöscht',
        INCORRECT_OLD_PASSWORD: 'Dein altes Passwort ist falsch.',
        AMOUNT_TOO_SMALL: 'Betrag ist zu gering',
        GIFTCARD_NOT_FOUND: 'Ungültiger Gutscheincode',
        GIFTCARD_APPLIED: 'Gutscheincode erfolgreich eingelöst',
        EMPLOYEE_EMAIL_ALREADY_EXISTS: 'Mitarbeiter mit dieser E-Mailwurde bereits hinzugefügt',
        EMPLOYEE_PHONE_ALREADY_EXISTS: 'Mitarbeiter mit dieser Telefonnummer wurde bereits hinzugefügt'
    },
    it: {
        EMPLOYEE_EMAIL_ALREADY_EXISTS: 'Employee with this email is already added',
        EMPLOYEE_PHONE_ALREADY_EXISTS: 'Employee with this phone number is already added',
        NOT_ALLOWED: "Nessun numero di telefono associato a questo account. Prova altri metodi di accesso.",
        NOT_FOUND: "Utente non trovato",
        EMAIL_ALREADY_EXISTS: "Questa e-mail esiste già",
        PHONE_ALREADY_EXISTS: "Questo numero di telefono esiste già",
        SIGNUP_SUCCESSFULLY: "Registrazione effettuata con successo. L'OTP è stato inviato al tuo numero di cellulare",
        OTP_SENT_SUCCESSFULLY: "L'OTP è stato inviato con successo",
        OTP_INVALID: "OTP non valido",
        OTP_LIMIT_EXHAUSTED: "Limite OTP esaurito. Riprova dopo 5 minuti",
        OTP_VERIFIED: "OTP verificato con successo",
        OTP_EXPIRED: "OTP scaduto",
        INCORRECT_PASSWORD: "La password non è corretta",
        LOGIN_SUCCESSFULLY: "Accesso utente avvenuto con SUCCESSO",
        ALREADY_BLOCKED: "L'utente è bloccato",
        USER_BLOCKED_SUCCESSFULLY: "L'utente è stato bloccato con successo",
        USER_ALREADY_ACTIVE: "L'utente è già attivo",
        USER_ALREADY_EXISTS: "L'utente è già attivo",
        COHOST_ALREADY_EXIST: "Hai già invitato questo utente come co-host.",
        COHOST_ALREADY_ASSOCIATED: "L'utente con questi dettagli è già associato a un altro account",
        USER_UNBLOCKED_SUCCESSFULLY: "Utente sbloccato con successo",
        USER_ALREADY_DELETED: "Utente già eliminato",
        USER_DELETED_SUCCESSFULLY: "Utente eliminato con successo",
        Email_NOT_VERIFIED: "L'email dell'utente non è stata verificata",
        PAYOUT_ALREADY_CREATED: "Già creato",
        Email_VERIFIED: "L'e-mail dell'utente è stata verificata con successo",
        MAIL_VERIFICATIO_LINK: "Link di verifica via posta inviato con successo",
        LINK_EXPIRED: "Il link di verifica è scaduto ",
        LINKEDIN_ERROR: "Errore di autorizzazione! si prega di riprovare.",
        PASSWORD_CHANGED_SUCCESSFULLY: "La tua password è stata modificata con successo. Effettua l'accesso per continuare.",
        ACCOUNT_BLOCKED: "Il tuo account è stato bloccato temporaneamente.",
        TOKEN_EXPIRED: "Token scaduto",
        LOGGED_OUT_SUCCESSFULLY: "Sei stato disconnesso da DeskNow",
        USER_FOUND_SUCCESSFULLY: "Informazioni utente",
        INVALID_RESET_TOKEN: "Token di ripristino non valido",
        VALID_RESET_TOKEN: "Token di ripristino valido",
        AMINTIES_LISTING: "Elenco dei servizi.",
        PARENT_CATEGORIES: "Elenco categorie principali",
        CHILD_CATEGORIES: "Elenco sottocategorie",
        NOT_EXISTS: "Non esiste",
        PHONE_NOT_VERIFIED: "Telefono non verificato.",
        HOST_EXISTS: "L'Host esiste.",
        USER_EXISTS: "L'utente esiste.",
        EXISTS: "Il numero di telefono esiste.",
        EMAIL_ALREADY_EXISTS_AS_HOST: "Questo indirizzo e-mail è già registrato come host",
        EMAIL_ALREADY_EXISTS_AS_USER: "Questo indirizzo e-mail è già registrato come utente",
        USER_EXISTS_AS_COMPANY: "L'utente esiste come azienda",
        INVALID_EMAIL: "E-mail non valida",
        COWORKER_EXISTS: "COLLEGA GIÀ INVITATO",
        USER_ELIGIBLE: "Utente idoneo come collega",
        USER_NOT_FOUND: "Utente non trovato",
        CHECK_SELF: "Non puoi aggiungere te stesso",
        CHECK_AVAILABILITY: "Non è possibile aggiungere altri colleghi. È stata raggiunta la massima capienza",
        ACCOUNT_DELETED: "Questo account è stato eliminato con successo.",
        INCORRECT_OLD_PASSWORD: "La tua vecchia password è errata",
        AMOUNT_TOO_SMALL: "Importo troppo piccolo",
        GIFTCARD_NOT_FOUND: "Numero di carta regalo non valido",
        GIFTCARD_APPLIED: "Carta regalo usata con successo"
    },
    pl: {
        EMPLOYEE_EMAIL_ALREADY_EXISTS: 'Employee with this email is already added',
        EMPLOYEE_PHONE_ALREADY_EXISTS: 'Employee with this phone number is already added',
        NOT_ALLOWED: "Z tym kontem nie jest powiązany żaden numer telefonu. Spróbuj innych metod logowania.",
        NOT_FOUND: "Nie znaleziono użytkownika",
        EMAIL_ALREADY_EXISTS: "Ten adres e-mail już istnieje",
        PHONE_ALREADY_EXISTS: "Ten numer telefonu już istnieje.",
        SIGNUP_SUCCESSFULLY: "Rejestracja pomyślna, hasło jednorazowe zostało wysłane na Twój numer telefonu komórkowego",
        OTP_SENT_SUCCESSFULLY: "Hasło jednorazowe zostało pomyślnie wysłane",
        OTP_INVALID: "Nieprawidłowe hasło jednorazowe",
        OTP_LIMIT_EXHAUSTED: "Limit hasła jednorazowego wyczerpany. Spróbuj ponownie za 5 minut",
        OTP_VERIFIED: "Hasło jednorazowe zostało pomyślnie zweryfikowane",
        OTP_EXPIRED: "Hasło jednorazowe wygasło",
        INCORRECT_PASSWORD: "Hasło jest nieprawidłowe",
        LOGIN_SUCCESSFULLY: "Użytkownik zalogował się POMYŚLNIE",
        ALREADY_BLOCKED: "Użytkownik jest zablokowany",
        USER_BLOCKED_SUCCESSFULLY: "Użytkownik został pomyślnie zablokowany",
        USER_ALREADY_ACTIVE: "Użytkownik jest już aktywny",
        USER_ALREADY_EXISTS: "Użytkownik jest już aktywny",
        COHOST_ALREADY_EXIST: "Już zaprosiłeś(aś) tego użytkownika jako współgospodarza.",
        COHOST_ALREADY_ASSOCIATED: "Użytkownik o tych danych jest już powiązany z innym kontem",
        USER_UNBLOCKED_SUCCESSFULLY: "Użytkownik został pomyślnie odblokowany ",
        USER_ALREADY_DELETED: "Użytkownik został już usunięty",
        USER_DELETED_SUCCESSFULLY: "Użytkownik został pomyślnie usunięty ",
        Email_NOT_VERIFIED: "Adres e-mail użytkownika nie jest zweryfikowany",
        PAYOUT_ALREADY_CREATED: "Już utworzone",
        Email_VERIFIED: "Adres e-mail użytkownika został pomyślnie zweryfikowany",
        MAIL_VERIFICATIO_LINK: "Link weryfikacyjny do poczty został pomyślnie wysłany",
        LINK_EXPIRED: "Link weryfikacyjny wygasł ",
        LINKEDIN_ERROR: "Błąd uwierzytelnienia! Spróbuj ponownie.",
        PASSWORD_CHANGED_SUCCESSFULLY: "Twoje hasło zostało pomyślnie zmienione. Zaloguj się, aby kontynuować.",
        ACCOUNT_BLOCKED: "Twoje konto zostało tymczasowo zablokowane.",
        TOKEN_EXPIRED: "Token wygasł",
        LOGGED_OUT_SUCCESSFULLY: "Zostałeś(aś) wylogowany(a) z DeskNow",
        USER_FOUND_SUCCESSFULLY: "Informacja dotycząca użytkownika",
        INVALID_RESET_TOKEN: "Nieprawidłowo zresetowany token",
        VALID_RESET_TOKEN: "Prawidłowo zresetowano token",
        AMINTIES_LISTING: "Lista udogodnień.",
        PARENT_CATEGORIES: "Lista kategorii nadrzędnych",
        CHILD_CATEGORIES: "Lista kategorii podrzędnych",
        NOT_EXISTS: "Nie istnieje",
        PHONE_NOT_VERIFIED: "Niezweryfikowany numer telefonu.",
        HOST_EXISTS: "Gospodarz istnieje.",
        USER_EXISTS: "Użytkownik istnieje.",
        EXISTS: "Numer telefonu istnieje.",
        EMAIL_ALREADY_EXISTS_AS_HOST: "Ten adres e-mail jest już zarejestrowany jako należący do gospodarza",
        EMAIL_ALREADY_EXISTS_AS_USER: "Ten adres e-mail jest już zarejestrowany jako należący do użytkownika",
        USER_EXISTS_AS_COMPANY: "Użytkownik istnieje jako firma",
        INVALID_EMAIL: "Nieprawidłowy adres e-mail",
        COWORKER_EXISTS: "WSPÓŁPRACOWNIK ZOSTAŁ JUŻ ZAPROSZONY",
        USER_ELIGIBLE: "Użytkownik może zostać współpracownikiem",
        USER_NOT_FOUND: "Nie znaleziono użytkownika",
        CHECK_SELF: "Nie możesz dodać siebie",
        CHECK_AVAILABILITY: "Nie możesz dodać więcej współpracowników. Pojemność została wyczerpana",
        ACCOUNT_DELETED: "Twoje konto zostało pomyślnie usunięte",
        INCORRECT_OLD_PASSWORD: "Twoje stare hasło jest nieprawidłowe",
        AMOUNT_TOO_SMALL: "Kwota zbyt mała",
        GIFTCARD_NOT_FOUND: "Nieprawidłowy numer karty podarunkowej",
        GIFTCARD_APPLIED: "Karta podarunkowa została pomyślnie zastosowana"
    },
    ro: {
        EMPLOYEE_EMAIL_ALREADY_EXISTS: 'Employee with this email is already added',
        EMPLOYEE_PHONE_ALREADY_EXISTS: 'Employee with this phone number is already added',
        NOT_ALLOWED: "Nu există niciun număr de telefon asociat cu acest cont. Încercați alte metode de conectare.",
        NOT_FOUND: "Utilizatorul nu a fost găsit",
        EMAIL_ALREADY_EXISTS: "Această adresă de e-mail este deja înregistrată",
        PHONE_ALREADY_EXISTS: "Acest număr de telefon este deja înregistrat",
        SIGNUP_SUCCESSFULLY: "Înregistrare reușită, parola unică a fost trimisă la numărul dvs. de mobil",
        OTP_SENT_SUCCESSFULLY: "OTP trimis cu succes",
        OTP_INVALID: "OTP incorect",
        OTP_LIMIT_EXHAUSTED: "Limită OTP depășită. Vă rugăm să încercați din nou peste 5 minute.",
        OTP_VERIFIED: "OTP verificat cu succes",
        OTP_EXPIRED: "OTP expirat",
        INCORRECT_PASSWORD: " Parolă incorectă",
        LOGIN_SUCCESSFULLY: "Autentificare utilizator REUȘITĂ.",
        ALREADY_BLOCKED: "Utilizator blocat",
        USER_BLOCKED_SUCCESSFULLY: "Utilizator blocat cu succes",
        USER_ALREADY_ACTIVE: "Utilizator deja activ",
        USER_ALREADY_EXISTS: "Utilizator deja activ",
        COHOST_ALREADY_EXIST: "Ați invitat deja acest utilizator ca co-gazdă.",
        COHOST_ALREADY_ASSOCIATED: "Utilizatorul cu aceste detalii este deja asociat cu un alt cont",
        USER_UNBLOCKED_SUCCESSFULLY: "Utilizator deblocat cu succes",
        USER_ALREADY_DELETED: "Utilizator deja șters",
        USER_DELETED_SUCCESSFULLY: "Utilizator șters cu succes",
        Email_NOT_VERIFIED: "Adresă de e-mail de utilizator neverificată",
        PAYOUT_ALREADY_CREATED: "Deja creat",
        Email_VERIFIED: "Adresă de e-mail utilizator verificată cu succes",
        MAIL_VERIFICATIO_LINK: "Link-ul de verificare a adresei de e-mail a fost trimis cu succes",
        LINK_EXPIRED: "Link de verificare expirat ",
        LINKEDIN_ERROR: "Eroare de autorizare! vă rugăm să reîncercați.",
        PASSWORD_CHANGED_SUCCESSFULLY: "Parola dvs. a fost modificată cu succes. Vă rugăm să vă conectați pentru a continua.",
        ACCOUNT_BLOCKED: "Contul dvs. a fost blocat temporar.",
        TOKEN_EXPIRED: "Token expirat",
        LOGGED_OUT_SUCCESSFULLY: "Ați fost deconectat de la DeskNow",
        USER_FOUND_SUCCESSFULLY: "Informații utilizator",
        INVALID_RESET_TOKEN: "Token de resetare incorect",
        VALID_RESET_TOKEN: "Token de resetare corect",
        AMINTIES_LISTING: "Lista de facilități.",
        PARENT_CATEGORIES: "Lista categoriilor părinte",
        CHILD_CATEGORIES: "Lista categoriilor copil",
        NOT_EXISTS: " Nu există",
        PHONE_NOT_VERIFIED: "Numărul de telefon nu a fost verificat.",
        HOST_EXISTS: "Gazda există.",
        USER_EXISTS: "Utilizatorul există.",
        EXISTS: "Numărul de telefon există.",
        EMAIL_ALREADY_EXISTS_AS_HOST: "Această adresă de e-mail este deja înregistrată ca gazdă",
        EMAIL_ALREADY_EXISTS_AS_USER: "Această adresă de e-mail este deja înregistrată ca utilizator",
        USER_EXISTS_AS_COMPANY: "Utilizatorul există ca companie",
        INVALID_EMAIL: "Adresă  de e-mail incorectă",
        COWORKER_EXISTS: "COWORKER DEJA INVITAT",
        USER_ELIGIBLE: "Utilizator eligibil pentru a fi coworker",
        USER_NOT_FOUND: "Utilizatorul nu a fost găsit",
        CHECK_SELF: "Nu vă puteți autoadăuga",
        CHECK_AVAILABILITY: "Nu mai puteți adăuga alți coworkeri. Capacitatea este plină",
        ACCOUNT_DELETED: "Contul dvs. a fost șters cu succes",
        INCORRECT_OLD_PASSWORD: "Parola veche este incorectă.",
        AMOUNT_TOO_SMALL: "Valoare prea mică",
        GIFTCARD_NOT_FOUND: "Număr de card cadou incorect",
        GIFTCARD_APPLIED: "Card cadou aplicat cu succes"
    },
    ru: {
        EMPLOYEE_EMAIL_ALREADY_EXISTS: 'Employee with this email is already added',
        EMPLOYEE_PHONE_ALREADY_EXISTS: 'Employee with this phone number is already added',
        NOT_ALLOWED: "С этим аккаунтом не связан ни один номер телефона. Попробуйте войти в систему другим способом.",
        NOT_FOUND: "Пользователь не найден",
        EMAIL_ALREADY_EXISTS: "Этот адрес электронной почты уже существует",
        PHONE_ALREADY_EXISTS: "Этот номер телефона уже существует",
        SIGNUP_SUCCESSFULLY: "Регистрация прошла успешно: одноразовый пароль отправлен на ваш номер телефона",
        OTP_SENT_SUCCESSFULLY: "Одноразовый пароль отправлен",
        OTP_INVALID: "Недействительный одноразовый пароль",
        OTP_LIMIT_EXHAUSTED: "Лимит одноразовых паролей исчерпан. Повторите попытку через 5 минут",
        OTP_VERIFIED: "Одноразовый пароль подтвержден",
        OTP_EXPIRED: "Срок действия одноразового пароля истек",
        INCORRECT_PASSWORD: "Неверный пароль",
        LOGIN_SUCCESSFULLY: "Вход ВЫПОЛНЕН",
        ALREADY_BLOCKED: "Пользователь заблокирован",
        USER_BLOCKED_SUCCESSFULLY: "Пользователь заблокирован",
        USER_ALREADY_ACTIVE: "Пользователь уже активен",
        USER_ALREADY_EXISTS: "Пользователь уже активен",
        COHOST_ALREADY_EXIST: "Вы уже пригласили этого пользователя в качестве совладельца.",
        COHOST_ALREADY_ASSOCIATED: "Пользователь с этими данными связан с другой учетной записью",
        USER_UNBLOCKED_SUCCESSFULLY: "Пользователь разблокирован",
        USER_ALREADY_DELETED: "Пользователь уже удален",
        USER_DELETED_SUCCESSFULLY: "Пользователь удален",
        Email_NOT_VERIFIED: "Электронная почта пользователя не проверена",
        PAYOUT_ALREADY_CREATED: "Уже создано",
        Email_VERIFIED: "Электронная почта пользователя проверена",
        MAIL_VERIFICATIO_LINK: "Ссылка для подтверждения электронной почты отправлена",
        LINK_EXPIRED: "Срок действия ссылки для подтверждения истек ",
        LINKEDIN_ERROR: "Ошибка авторизации! повторите попытку.",
        PASSWORD_CHANGED_SUCCESSFULLY: "Пароль изменен. Войдите для продолжения.",
        ACCOUNT_BLOCKED: "Ваш аккаунт временно заблокирован.",
        TOKEN_EXPIRED: "Срок действия токена истек",
        LOGGED_OUT_SUCCESSFULLY: "Вы вышли из DeskNow",
        USER_FOUND_SUCCESSFULLY: "Информация о пользователе",
        INVALID_RESET_TOKEN: "Недействительный токен для сброса",
        VALID_RESET_TOKEN: "Действительный токен для сброса",
        AMINTIES_LISTING: "Список удобств.",
        PARENT_CATEGORIES: "Список родительских категорий",
        CHILD_CATEGORIES: "Список дочерних категорий",
        NOT_EXISTS: "Не существует",
        PHONE_NOT_VERIFIED: "Телефон не проверен.",
        HOST_EXISTS: "Владелец уже существует.",
        USER_EXISTS: "Пользователь уже существует.",
        EXISTS: "Номер телефона уже существует.",
        EMAIL_ALREADY_EXISTS_AS_HOST: "Эта электронная почта уже зарегистрирована на владельца",
        EMAIL_ALREADY_EXISTS_AS_USER: "Эта электронная почта уже зарегистрирована на пользователя",
        USER_EXISTS_AS_COMPANY: "Пользователь зарегистрирован как компания",
        INVALID_EMAIL: "Недействительный адрес электронной почты",
        COWORKER_EXISTS: "КОЛЛЕГА УЖЕ ПРИГЛАШЕН(-А)",
        USER_ELIGIBLE: "Пользователь может стать коллегой",
        USER_NOT_FOUND: "Пользователь не найден",
        CHECK_SELF: "Вы не можете добавить себя",
        CHECK_AVAILABILITY: "Вы не можете добавить больше коллег. Мест не осталось",
        ACCOUNT_DELETED: "Ваша учетная запись удалена",
        INCORRECT_OLD_PASSWORD: "Неверный старый пароль",
        AMOUNT_TOO_SMALL: "Сумма слишком маленькая",
        GIFTCARD_NOT_FOUND: "Неверный номер подарочной карты",
        GIFTCARD_APPLIED: "Подарочная карта применена"
    },
    es: {
        EMPLOYEE_EMAIL_ALREADY_EXISTS: 'Employee with this email is already added',
        EMPLOYEE_PHONE_ALREADY_EXISTS: 'Employee with this phone number is already added',
        NOT_ALLOWED: "No hay ningún número de teléfono asociado a esta cuenta. Prueba otros métodos de inicio de sesión.",
        NOT_FOUND: "Usuario no encontrado",
        EMAIL_ALREADY_EXISTS: "Este correo ya existe",
        PHONE_ALREADY_EXISTS: "Este número de teléfono ya existe",
        SIGNUP_SUCCESSFULLY: "Registro completado correctamente; la contraseña de un solo uso se ha enviado a tu número de teléfono",
        "OTP_SENT_SUCCESSFULLY": "El código OTP se ha enviado correctamente",
        OTP_INVALID: "Codigo OTP no válido",
        OTP_LIMIT_EXHAUSTED: "Se ha agotado el límite del código OTP. Vuelve a intentarlo en 5 minutos",
        OTP_VERIFIED: "El código OTP se ha verificado correctamente",
        OTP_EXPIRED: "El código OTP ha caducado",
        INCORRECT_PASSWORD: "La contraseña es incorrecta ",
        LOGIN_SUCCESSFULLY: "Sesión de usuario iniciada CORRECTAMENTE",
        ALREADY_BLOCKED: "El usuario está bloqueado",
        USER_BLOCKED_SUCCESSFULLY: "El usuario se ha bloqueado correctamente",
        USER_ALREADY_ACTIVE: "Este usuario ya está activo",
        USER_ALREADY_EXISTS: "Este usuario ya está activo",
        COHOST_ALREADY_EXIST: "Ya has invitado a este usuario como coanfitrión.",
        COHOST_ALREADY_ASSOCIATED: "Los datos de este usuario ya están asociados con otra cuenta",
        USER_UNBLOCKED_SUCCESSFULLY: "El usuario se ha desbloqueado correctamente",
        USER_ALREADY_DELETED: "El usuario ya se ha eliminado",
        USER_DELETED_SUCCESSFULLY: "El usuario se ha eliminado correctamente",
        Email_NOT_VERIFIED: "El correo electrónico del usuario no está verificado",
        PAYOUT_ALREADY_CREATED: "Ya creado",
        Email_VERIFIED: "El correo electrónico del usuario se ha verificado correctamente",
        MAIL_VERIFICATIO_LINK: "El enlace de verificación de correo se ha enviado correctamente",
        LINK_EXPIRED: "El enlace de verificación ha caducado ",
        LINKEDIN_ERROR: "¡Error de autorización! Inténtalo de nuevo.",
        PASSWORD_CHANGED_SUCCESSFULLY: "Tu contraseña se ha cambiado correctamente. Inicia sesión para continuar.",
        ACCOUNT_BLOCKED: "Tu cuenta ha sido bloqueada temporalmente.",
        TOKEN_EXPIRED: "Token caducado",
        LOGGED_OUT_SUCCESSFULLY: "Has cerrado la sesión de DeskNow",
        USER_FOUND_SUCCESSFULLY: "Información del usuario",
        INVALID_RESET_TOKEN: "Token de reinicio no válido",
        VALID_RESET_TOKEN: "Token de reinicio válido",
        AMINTIES_LISTING: "Lista de servicios.",
        PARENT_CATEGORIES: "Lista de categorías principales",
        CHILD_CATEGORIES: "Lista de categorías secundarias",
        NOT_EXISTS: "No existe",
        PHONE_NOT_VERIFIED: "Teléfono no verificado",
        HOST_EXISTS: "El anfitrión existe.",
        USER_EXISTS: "El usuario existe.",
        EXISTS: "El número de teléfono existe.",
        EMAIL_ALREADY_EXISTS_AS_HOST: "Este correo electrónico ya está registrado como anfitrión",
        EMAIL_ALREADY_EXISTS_AS_USER: "Este correo electrónico ya está registrado como usuario",
        USER_EXISTS_AS_COMPANY: "El usuario existe como empresa",
        INVALID_EMAIL: "Correo electrónico no válido",
        COWORKER_EXISTS: "COWORKER YA INVITADO",
        USER_ELIGIBLE: "Usuario elegible como coworker",
        USER_NOT_FOUND: "Usuario no encontrado",
        CHECK_SELF: "No puedes agregarte a ti mismo",
        CHECK_AVAILABILITY: "No puedes añadir a más coworkers. La capacidad está completa",
        ACCOUNT_DELETED: "Tu cuenta se ha eliminado correctamente",
        INCORRECT_OLD_PASSWORD: "Tu contraseña antigua es incorrecta",
        AMOUNT_TOO_SMALL: "El importe es demasiado pequeño",
        GIFTCARD_NOT_FOUND: "Número de tarjeta regalo no válido",
        GIFTCARD_APPLIED: "La tarjeta regalo se ha aplicado correctamente"
    },
    tr: {
        EMPLOYEE_EMAIL_ALREADY_EXISTS: 'Employee with this email is already added',
        EMPLOYEE_PHONE_ALREADY_EXISTS: 'Employee with this phone number is already added',
        NOT_ALLOWED: "Bu hesapla ilişkilendirilmiş telefon numarası yok. Lütfen diğer giriş yöntemlerini deneyin.",
        NOT_FOUND: "Kullanıcı bulunamadı",
        EMAIL_ALREADY_EXISTS: "Bu e-posta zaten var",
        PHONE_ALREADY_EXISTS: "Bu telefon numarası zaten var",
        SIGNUP_SUCCESSFULLY: "Kaydınızı tamamlayın. Mobil numaranıza tek kullanımlık parola (OTP) gönderildi",
        OTP_SENT_SUCCESSFULLY: "OTP gönderme işlemi tamam",
        OTP_INVALID: "Geçersiz OTP",
        OTP_LIMIT_EXHAUSTED: "OTP limiti doldu. Lütfen 5 dakika sonra tekrar deneyin",
        OTP_VERIFIED: "OTP doğrulama tamam",
        OTP_EXPIRED: "OTP'nin süresi doldu",
        INCORRECT_PASSWORD: "Parola yanlış",
        LOGIN_SUCCESSFULLY: "Kullanıcı Girişi TAMAM",
        ALREADY_BLOCKED: "Kullanıcı engellendi",
        USER_BLOCKED_SUCCESSFULLY: "Kullanıcı engelleme işlemi tamam",
        USER_ALREADY_ACTIVE: "Kullanıcı zaten etkin",
        USER_ALREADY_EXISTS: "Kullanıcı zaten etkin",
        COHOST_ALREADY_EXIST: "Bu kullanıcıyı eş sunucu olarak önceden davet etmiştiniz.",
        COHOST_ALREADY_ASSOCIATED: "Bu bilgiler bir başka kullanıcı hesabıyla ilişkilendirilmiş durumda",
        USER_UNBLOCKED_SUCCESSFULLY: "Kullanıcının engeli kaldırıldı",
        USER_ALREADY_DELETED: "Kullanıcı zaten silinmiş",
        USER_DELETED_SUCCESSFULLY: "Kullanıcı silme işlemi tamam",
        Email_NOT_VERIFIED: "Kullanıcı E-postası Doğrulanmadı",
        PAYOUT_ALREADY_CREATED: "Zaten oluşturulmuş",
        Email_VERIFIED: "Kullanıcı E-postası Doğrulanmıştır",
        MAIL_VERIFICATIO_LINK: "Posta doğrulama bağlantısı gönderilmiştir",
        LINK_EXPIRED: "Doğrulama Bağlantısının Süresi Dolmuş ",
        LINKEDIN_ERROR: "Yetkilendirme hatası! Lütfen tekrar deneyin.",
        PASSWORD_CHANGED_SUCCESSFULLY: "Parolanız değiştirilmiştir. Devam etmek için lütfen giriş yapın.",
        ACCOUNT_BLOCKED: "Hesabınız geçici olarak bloke edilmiştir.",
        TOKEN_EXPIRED: "Jetonun Süresi Doldu",
        LOGGED_OUT_SUCCESSFULLY: "DeskNow oturumunuz sona erdi",
        USER_FOUND_SUCCESSFULLY: "Kullanıcı Bilgileri",
        INVALID_RESET_TOKEN: "Geçersiz sıfırlama jetonu",
        VALID_RESET_TOKEN: "Geçerli sıfırlama jetonu",
        AMINTIES_LISTING: "Olanakların listesi.",
        PARENT_CATEGORIES: "Üst kategorilerin listesi",
        CHILD_CATEGORIES: "Alt kategorilerin listesi",
        NOT_EXISTS: "Yok",
        PHONE_NOT_VERIFIED: "Telefon doğrulanmadı.",
        HOST_EXISTS: "Mekân sunucu var.",
        USER_EXISTS: "Kullanıcı var.",
        EXISTS: "Telefon Numarası Var.",
        EMAIL_ALREADY_EXISTS_AS_HOST: "Bu e-posta adresi mekân sunucu olarak zaten kayıtlı",
        EMAIL_ALREADY_EXISTS_AS_USER: "Bu e-posta adresi kullanıcı olarak zaten kayıtlı",
        USER_EXISTS_AS_COMPANY: "Kullanıcı şirket olarak kayıtlı",
        INVALID_EMAIL: "Geçersiz E-posta",
        COWORKER_EXISTS: "ORTAK ÇALIŞAN ZATEN DAVET EDİLMİŞ",
        USER_ELIGIBLE: "Kullanıcı, ortak çalışan olabilir",
        USER_NOT_FOUND: "Kullanıcı bulunamadı",
        CHECK_SELF: "Kendinizi ekleyemezsiniz",
        CHECK_AVAILABILITY: "Başka ortak çalışan ekleyemezsiniz. Kapasite doldu",
        ACCOUNT_DELETED: "Hesabınız tamamen silinmiştir",
        INCORRECT_OLD_PASSWORD: "Eski parolanız yanlış",
        AMOUNT_TOO_SMALL: "Miktar çok küçük",
        GIFTCARD_NOT_FOUND: "Geçersiz Hediye Kartı Numarası",
        GIFTCARD_APPLIED: "Hediye Kartı Uygulanmıştır"
    }
}



export default (lang: string) => ({
    NOT_FOUND: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].NOT_FOUND },
    USER_NOT_FOUND: { httpCode: HTTP.BAD_REQUEST, statusCode: 412, message: MSG[lang].USER_NOT_FOUND },
    Link_EXPIRED: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].LINK_EXPIRED },
    Email_NOT_VERIFIED: { httpCode: HTTP.NOT_VERIFIED, statusCode: 410, message: MSG[lang].Email_NOT_VERIFIED },
    Email_VERIFIED: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].Email_VERIFIED },
    USER_ELIGIBLE: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].USER_ELIGIBLE },
    PHONE_ALREADY_EXISTS: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].PHONE_ALREADY_EXISTS },
    LINKEDIN_ERROR: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].LINKEDIN_ERROR },
    EMAIL_ALREADY_EXISTS: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].EMAIL_ALREADY_EXISTS },
    EMAIL_ALREADY_EXISTS_AS_HOST: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].EMAIL_ALREADY_EXISTS_AS_HOST },
    USER_EXISTS_AS_COMPANY: { httpCode: HTTP.USER_ALREADY_EXISTS, statusCode: 422, message: MSG[lang].USER_EXISTS_AS_COMPANY },
    EMAIL_ALREADY_EXISTS_AS_USER: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].EMAIL_ALREADY_EXISTS_AS_USER },
    SIGNUP_SUCCESSFULLY: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].SIGNUP_SUCCESSFULLY },
    EXISTS: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].EXISTS },
    LOGIN_SUCCESSFULLY: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].LOGIN_SUCCESSFULLY },
    OTP_SENT_SUCCESSFULLY: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].OTP_SENT_SUCCESSFULLY },
    MAIL_VERIFICATIO_LINK: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].MAIL_VERIFICATIO_LINK },
    OTP_INVALID: { httpCode: HTTP.BAD_REQUEST, statusCode: 409, message: MSG[lang].OTP_INVALID },
    OTP_LIMIT_EXHAUSTED: { httpCode: HTTP.BAD_REQUEST, statusCode: 409, message: MSG[lang].OTP_LIMIT_EXHAUSTED },
    OTP_EXPIRED: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].OTP_EXPIRED },
    TOKEN_EXPIRED: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].TOKEN_EXPIRED },
    OTP_VERIFIED: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].OTP_VERIFIED },
    ACCOUNT_DELETED: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].ACCOUNT_DELETED },
    INCORRECT_PASSWORD: { httpCode: HTTP.BAD_REQUEST, statusCode: 413, message: MSG[lang].INCORRECT_PASSWORD },
    INCORRECT_OLD_PASSWORD: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].INCORRECT_OLD_PASSWORD },
    USER_BLOCKED_SUCCESSFULLY: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].USER_BLOCKED_SUCCESSFULLY },
    PASSWORD_CHANGED_SUCCESSFULLY: { httpCode: HTTP.SUCCESS, statusCode: 204, message: MSG[lang].PASSWORD_CHANGED_SUCCESSFULLY },
    ALREADY_BLOCKED: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].ALREADY_BLOCKED },
    USER_UNBLOCKED_SUCCESSFULLY: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].USER_UNBLOCKED_SUCCESSFULLY },
    USER_ALREADY_ACTIVE: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].USER_ALREADY_ACTIVE },
    COWORKER_EXISTS: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].COWORKER_EXISTS },
    CHECK_SELF: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].CHECK_SELF },
    CHECK_AVAILABILITY: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].CHECK_AVAILABILITY },
    USER_ALREADY_EXISTS: { httpCode: HTTP.USER_ALREADY_EXISTS, statusCode: 422, message: MSG[lang].USER_ALREADY_EXISTS },
    COHOST_ALREADY_EXIST: { httpCode: HTTP.USER_ALREADY_EXISTS, statusCode: 422, message: MSG[lang].COHOST_ALREADY_EXIST },
    COHOST_ALREADY_ASSOCIATED: { httpCode: HTTP.USER_ALREADY_EXISTS, statusCode: 422, message: MSG[lang].COHOST_ALREADY_ASSOCIATED },
    HOST_EXISTS: { httpCode: HTTP.USER_ALREADY_EXISTS, statusCode: 422, message: MSG[lang].HOST_EXISTS },
    USER_EXISTS: { httpCode: HTTP.USER_ALREADY_EXISTS, statusCode: 422, message: MSG[lang].USER_EXISTS },
    NOT_ALLOWED: { httpCode: HTTP.NOT_ALLOWED, statusCode: 405, message: MSG[lang].NOT_ALLOWED },
    USER_ALREADY_DELETED: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].USER_ALREADY_DELETED },
    USER_DELETED_SUCCESSFULLY: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].USER_DELETED_SUCCESSFULLY },
    ACCOUNT_BLOCKED: { httpCode: HTTP.ACCOUNT_BLOCKED, statusCode: 409, message: MSG[lang].ACCOUNT_BLOCKED },
    USER_FOUND_SUCCESSFULLY: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].USER_FOUND_SUCCESSFULLY },
    AMINTIES_LISTING: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].AMINTIES_LISTING },
    PARENT_CATEGORIES: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].PARENT_CATEGORIES },
    CHILD_CATEGORIES: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].CHILD_CATEGORIES },
    LOGGED_OUT_SUCCESSFULLY: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].LOGGED_OUT_SUCCESSFULLY },
    INVALID_RESET_TOKEN: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].INVALID_RESET_TOKEN },
    VALID_RESET_TOKEN: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].VALID_RESET_TOKEN },
    NOT_EXISTS: { httpCode: HTTP.EMAIl_NOT_EXISTS, statusCode: 411, message: MSG[lang].NOT_EXISTS },
    PHONE_NOT_VERIFIED: { httpCode: HTTP.UNAUTHORIZED, statusCode: 401, message: MSG[lang].PHONE_NOT_VERIFIED },
    INVALID_EMAIL: { httpCode: HTTP.BAD_REQUEST, statusCode: 412, message: MSG[lang].INVALID_EMAIL },
    PAYOUT_ALREADY_CREATED: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].PAYOUT_ALREADY_CREATED },
    CARD_LIST: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].CARD_LIST },
    CARD_EXIST: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].CARD_EXIST },
    CARD_DELETED_SUCCESSFULLY: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].CARD_DELETED_SUCCESSFULLY },
    PAYMENT_SUCCESFULL: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].PAYMENT_SUCCESFULL },
    UPDATE_CARD: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].UPDATE_CARD },
    CUSTOMER_CREATED: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].CUSTOMER_CREATED },
    AMOUNT_TOO_SMALL: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].AMOUNT_TOO_SMALL },
    GIFTCARD_NOT_FOUND: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].GIFTCARD_NOT_FOUND },
    GIFTCARD_APPLIED: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG[lang].CUSTOMER_CREATED },
    EMPLOYEE_EMAIL_ALREADY_EXISTS: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].EMPLOYEE_EMAIL_ALREADY_EXISTS },
    EMPLOYEE_PHONE_ALREADY_EXISTS: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG[lang].EMPLOYEE_PHONE_ALREADY_EXISTS },

});

export const CUSTOM_SUCCESS = (data?: any, message?: string) => {
    return ({
        httpCode: 200,
        statusCode: 200,
        message: message ? message : "Success",
        data: data ? data : {}
    })
}

export const CUSTOM_ERROR = (data?: any, message?: string) => {
    return ({
        httpCode: 400,
        statusCode: 400,
        message: message ? message : "Success",
        data: data ? data : {}
    })
}