import { ENUM } from "./enum.common";

export async function notificationPayload(data: any, bookingId?: any) {
    return {
        TYPE: {
            BOOKING_SUCCESS: ENUM.NOTIFICATION_TYPE.BOOKING_SUCCESS_USER,
            BOOKING_SUCCESS_HOST: ENUM.NOTIFICATION_TYPE.BOOKING_SUCCESS_HOST,
            BOOKING_REQUEST_HOST: ENUM.NOTIFICATION_TYPE.BOOKING_REQUEST_HOST,
            BOOKING_REQUEST_USER: ENUM.NOTIFICATION_TYPE.BOOKING_REQUEST_USER,
            BOOKING_REQUEST_ACCEPTED_HOST: ENUM.NOTIFICATION_TYPE.BOOKING_REQUEST_ACCEPTED_HOST,
            BOOKING_REQUEST_ACCEPTED_USER: ENUM.NOTIFICATION_TYPE.BOOKING_REQUEST_ACCEPTED_USER,
            BOOKING_REQUEST_REJECTED_HOST: ENUM.NOTIFICATION_TYPE.BOOKING_REQUEST_REJECTED_HOST,
            BOOKING_REQUEST_REJECTED_USER: ENUM.NOTIFICATION_TYPE.BOOKING_REQUEST_REJECTED_USER,
            BOOKING_CANCELLED_USER: ENUM.NOTIFICATION_TYPE.BOOKING_CANCELLED_USER,
            BOOKING_CANCELLED_HOST: ENUM.NOTIFICATION_TYPE.BOOKING_CANCELLED_HOST,
            USER_PB_VERIFICATION_SUCCESS: ENUM.NOTIFICATION_TYPE.USER_PB_VERIFICATION_SUCCESS,
            USER_PB_VERIFICATION_FALSE: ENUM.NOTIFICATION_TYPE.USER_PB_VERIFICATION_FALSE,
            USER_SCHEDULED_DEMO: ENUM.NOTIFICATION_TYPE.SCHEDULED_DEMO,
            HOST_SCHEDULED_DEMO: ENUM.NOTIFICATION_TYPE.SCHEDULED_DEMO,
            HOST_SCHEDULED_DEMO_STATUS_ACCEPT: ENUM.NOTIFICATION_TYPE.SCHEDULED_DEMO,
            HOST_SCHEDULED_DEMO_STATUS_REJECT: ENUM.NOTIFICATION_TYPE.SCHEDULED_DEMO,
            USER_SCHEDULED_DEMO_STATUS_REJECT: ENUM.NOTIFICATION_TYPE.SCHEDULED_DEMO,
            USER_SCHEDULED_DEMO_STATUS_ACCEPT: ENUM.NOTIFICATION_TYPE.SCHEDULED_DEMO,
        },
        TITLE: {
            BOOKING_SUCCESS: 'Property booked successfully',
            BOOKING_SUCCESS_HOST: `Your have a new booking`,
            BOOKING_REQUEST_HOST: 'You have a new booking request',
            BOOKING_REQUEST_USER: 'Your booking request is pending!',
            BOOKING_REQUEST_ACCEPTED_HOST: 'Booking accepted',
            BOOKING_REQUEST_ACCEPTED_USER: 'Booking accepted',
            BOOKING_REQUEST_REJECTED_HOST: 'Booking rejected',
            BOOKING_REQUEST_REJECTED_USER: 'Booking rejected',
            BOOKING_CANCELLED_USER: 'Booking cancelled',
            BOOKING_CANCELLED_HOST: 'Booking cancelled',
            USER_PB_VERIFICATION_SUCCESS: `Profile verification success`,
            USER_PB_VERIFICATION_FALSE: `Profile verification failed`,
            BOOKING_CANCELLED_BY_HOST: `Booking cancelled`,
            BOOKING_CANCELLED_BY_HOST_TO_USER: `Booking cancelled`,
            USER_SCHEDULED_DEMO: `Demo scheduled successfully`,
            HOST_SCHEDULED_DEMO: `You got a new demo scheduled`,
            HOST_SCHEDULED_DEMO_STATUS_ACCEPT: `You got a new update on demo`,
            HOST_SCHEDULED_DEMO_STATUS_REJECT: `You got a new update on demo`,
            USER_SCHEDULED_DEMO_STATUS_REJECT: `You got a new update on demo`,
            USER_SCHEDULED_DEMO_STATUS_ACCEPT: `You got a new update on demo`,
        },
        BODY: {
            BOOKING_SUCCESS: `Your Booking for Property ${data} has been confirmed`,
            BOOKING_SUCCESS_HOST: `You have a new booking for property ${data}`,
            BOOKING_REQUEST_HOST: `You have a new booking request for property ${data}`,
            BOOKING_REQUEST_USER: `Your booking for property ${data} is pending please wait until it's confirmed`,
            BOOKING_REQUEST_ACCEPTED_HOST: `You successfully accepted booking for ${bookingId} of property ${data}`,
            BOOKING_REQUEST_ACCEPTED_USER: `Your booking ${bookingId} is accepted successfully of property ${data}`,
            BOOKING_REQUEST_REJECTED_HOST: `You have rejected booking for ${bookingId} of property ${data}`,
            BOOKING_REQUEST_REJECTED_USER: `Your booking ${bookingId} is rejected of property ${data}`,
            BOOKING_CANCELLED_USER: `Your booking ${bookingId} has been cancelled successfully of property ${data}`,
            BOOKING_CANCELLED_HOST: `Booking ${bookingId} has been cancelled by user of property ${data}`,
            USER_PB_VERIFICATION_SUCCESS: `Your profile has been successfully verified.`,
            USER_PB_VERIFICATION_FALSE: `Your profile verification has been failed.`,
            BOOKING_CANCELLED_BY_HOST: `Booking ${bookingId} has been cancelled of property ${data}.`,
            BOOKING_CANCELLED_BY_HOST_TO_USER: `Booking ${bookingId} has been cancelled of property ${data}.`,
            USER_SCHEDULED_DEMO: `Demo scheduled successfully for property ${data}`,
            HOST_SCHEDULED_DEMO: `You got a new demo scheduled for property ${data}`,
            HOST_SCHEDULED_DEMO_STATUS_ACCEPT: `You accepted demo for property ${data}`,
            HOST_SCHEDULED_DEMO_STATUS_REJECT: `You rejected demo for property ${data}`,
            USER_SCHEDULED_DEMO_STATUS_REJECT: `Your demo has been rejected by host for property ${data}`,
            USER_SCHEDULED_DEMO_STATUS_ACCEPT: `Your demo has been accepted by host for property ${data}`,
        },
        MESSAGE: {
            BOOKING_SUCCESS: `Property booked successfully`,
            BOOKING_SUCCESS_HOST: `You have a new booking`,
            BOOKING_REQUEST_HOST: `You have a new booking request`,
            BOOKING_REQUEST_USER: `Your booking request submitted successfully`,
            BOOKING_REQUEST_ACCEPTED_HOST: `You successfully accepted booking for ${bookingId} of property ${data}`,
            BOOKING_REQUEST_ACCEPTED_USER: `Your booking ${bookingId} is accepted successfully of property ${data}`,
            BOOKING_REQUEST_REJECTED_HOST: `You have rejected booking for ${bookingId} of property ${data}`,
            BOOKING_REQUEST_REJECTED_USER: `Your booking ${bookingId} is rejected of property ${data}`,
            BOOKING_CANCELLED_USER: `Your booking ${bookingId} has been cancelled successfully of property ${data}`,
            BOOKING_CANCELLED_HOST: `Booking ${bookingId} has been cancelled by user of property ${data}`,
            USER_PB_VERIFICATION: `Your profile has been ${data} verified.`,
            USER_PB_VERIFICATION_SUCCESS: `Your profile has been successfully verified.`,
            USER_PB_VERIFICATION_FALSE: `Your profile verification has been failed`,
            BOOKING_CANCELLED_BY_HOST: `Booking ${bookingId} has been cancelled of property ${data}.`,
            BOOKING_CANCELLED_BY_HOST_TO_USER: `Booking ${bookingId} has been cancelled of property ${data}.`,
            USER_SCHEDULED_DEMO: `Your demo request was successfully sent to the host. We will contact you asap with his reply`,
            HOST_SCHEDULED_DEMO: `You got a new demo scheduled for property ${data}`,
            HOST_SCHEDULED_DEMO_STATUS_ACCEPT: `You accepted demo for property ${data}`,
            HOST_SCHEDULED_DEMO_STATUS_REJECT: `You rejected demo for property ${data}`,
            USER_SCHEDULED_DEMO_STATUS_REJECT: `You demo has been rejected by host for property ${data}`,
            USER_SCHEDULED_DEMO_STATUS_ACCEPT: `Your demo has been accepted by host for property ${data}`,
        }
    }
}